D = {
"home": "Summerville personal injury attorneys at Frost Law Group help injured people across eight South Carolina counties. Call for a free, confidential consultation.",
"loc": "South Carolina personal injury attorneys at Frost Law Group serve eight counties from our Summerville office. Find your county and call for a free consultation.",
"car": "Car Accident Attorneys in Summerville at Frost Law Group explain South Carolina fault rules, insurance, and deadlines after a wreck. Call for a free review.",
"truck": "Truck Accident Attorneys in Summerville at Frost Law Group review federal trucking rules, carrier records, and insurance after a crash. Call for a free review.",
"moto": "Motorcycle Accident Attorneys in Summerville at Frost Law Group handle left turn, lane, and uninsured driver crashes in the Lowcountry. Call to talk today.",
"ride": "Rideshare Accident Attorneys in Summerville at Frost Law Group sort out app status, coverage, and fault after an Uber or Lyft crash. Call for a free review.",
"slip": "Slip and Fall Attorneys in Summerville at Frost Law Group explain what South Carolina law asks you to prove after a fall on someone's property. Call today.",
"dog": "Dog Bite Attorneys in Summerville at Frost Law Group explain South Carolina's strict liability statute and who pays after an attack. Call for a free review.",
"wd": "Wrongful Death Attorneys in Summerville at Frost Law Group guide families through South Carolina's wrongful death and survival claims. Call to talk with us.",
"co-dorchester": "Personal Injury Attorneys in Dorchester County at Frost Law Group handle crash and injury claims from St. George to Ridgeville. Call for a free consultation.",
"co-charleston": "Personal Injury Attorneys in Charleston County at Frost Law Group handle serious crash claims from North Charleston to the islands. Call for a free review.",
"co-berkeley": "Personal Injury Attorneys in Berkeley County at Frost Law Group handle crash claims from Goose Creek to Moncks Corner. Call for a free, confidential review.",
"co-colleton": "Personal Injury Attorneys in Colleton County at Frost Law Group handle I-95 and rural road crash claims around Walterboro. Call for a free, confidential review.",
"co-orangeburg": "Personal Injury Attorneys in Orangeburg County at Frost Law Group handle I-26 and I-95 crash claims in the same circuit as Summerville. Call for a free review.",
"co-beaufort": "Personal Injury Attorneys in Beaufort County at Frost Law Group handle crash and injury claims from Bluffton to the Sea Islands. Call for a free consultation.",
"co-georgetown": "Personal Injury Attorneys in Georgetown County at Frost Law Group handle US 17 and rural crash claims from Murrells Inlet to Andrews. Call for a free review.",
"co-williamsburg": "Personal Injury Attorneys in Williamsburg County at Frost Law Group handle rural crash claims around Kingstree, Hemingway, and Lane. Call for a free review.",
"car-dui": "Drunk Driving Accident Lawyers in Summerville at Frost Law Group explain the 2026 changes to South Carolina DUI crash claims. Call for a free consultation.",
"car-cat": "Catastrophic Injury Lawyers in Summerville at Frost Law Group document lifetime care, lost earning capacity, and coverage limits after a crash. Call us today.",
"car-hr": "Hit and Run Accident Lawyers in Summerville at Frost Law Group use your uninsured motorist coverage when a driver flees. Call for a free, confidential review.",
"truck-tt": "Tractor Trailer Accident Lawyers in Summerville at Frost Law Group examine the rig, the load, and the logbook after a semi crash. Call for a free review today.",
"truck-deliv": "Delivery Truck Accident Lawyers in Summerville at Frost Law Group handle van and box truck crash claims on local roads and main routes. Call for a free review.",
"truck-fatigue": "Truck Driver Fatigue Accident Lawyers in Summerville at Frost Law Group rebuild a trucker's duty day from logs and ELD data. Call for a free consultation.",
"moto-left": "Left Turn Motorcycle Accident Lawyers in Summerville at Frost Law Group prove when a driver turned into a rider's path. Call for a free, confidential review.",
"moto-helmet": "Motorcycle Helmet Law Injury Lawyers in Summerville at Frost Law Group explain what Section 56-5-3660 requires and how helmet questions arise. Call to talk.",
"moto-um": "Uninsured Motorist Motorcycle Lawyers in Summerville at Frost Law Group use your own policy when the other driver has no insurance. Call for a free review.",
"ride-uber": "Uber Accident Lawyers in Summerville at Frost Law Group handle claims for passengers, drivers, and others hurt in an Uber crash. Call for a free consultation.",
"ride-lyft": "Lyft Accident Lawyers in Summerville at Frost Law Group hold Lyft and its drivers to South Carolina's rideshare rules after a crash. Call for a free review.",
"slip-retail": "Retail Slip and Fall Lawyers in Summerville at Frost Law Group prove what a store knew about the hazard that caused your fall. Call for a free consultation.",
"slip-apt": "Apartment Injury Lawyers in Summerville at Frost Law Group explain landlord duties under South Carolina's landlord and tenant law. Call for a free review today.",
"slip-prem": "Premises Liability Lawyers in Summerville at Frost Law Group handle injuries from falling objects, broken stairs, and poor security. Call for a free review.",
"dog-strict": "Dog Bite Strict Liability Lawyers in Summerville at Frost Law Group read Section 47-3-110 line by line to show who is liable. Call for a free consultation.",
"dog-child": "Child Dog Bite Injury Lawyers in Summerville at Frost Law Group protect a child's claim through treatment, deadlines, and court approval. Call for a review.",
"dog-ins": "Dog Bite Insurance Claim Lawyers in Summerville at Frost Law Group pursue the owner's policy so you are not suing a neighbor. Call for a free, private review.",
"wd-car": "Fatal Car Accident Lawyers in Summerville at Frost Law Group answer a family's first questions after a deadly crash. Call for a free, confidential consultation.",
"wd-survival": "Survival Action Lawyers in Summerville at Frost Law Group pursue what a loved one suffered before death under South Carolina law. Call for a free review today.",
"wd-truck": "Fatal Truck Accident Lawyers in Summerville at Frost Law Group examine the carrier's hiring, testing, maintenance, and logs after a deadly crash. Call today.",
"chs-car": "Car Accident Lawyers in Charleston County at Frost Law Group prove distraction, failure to yield, and tailgating after a wreck. Call for a free consultation.",
"chs-truck": "Truck Accident Lawyers in Charleston County at Frost Law Group handle semi and commercial vehicle crash claims on I-26, I-526, and US 52. Call for a review.",
"chs-moto": "Motorcycle Accident Lawyers in Charleston County at Frost Law Group document serious rider injuries and pursue every available policy. Call for a review.",
"brk-car": "Car Accident Lawyers in Berkeley County at Frost Law Group handle speed, lane change, and run off road crash claims from Goose Creek to Moncks Corner. Call us.",
"brk-truck": "Truck Accident Lawyers in Berkeley County at Frost Law Group handle semi, gravel truck, and commercial vehicle crash claims on I-26 and US 52. Call for a review.",
"brk-moto": "Motorcycle Accident Lawyers in Berkeley County at Frost Law Group handle rider injury claims across Goose Creek, Hanahan, and Moncks Corner. Call for a review.",
"pa": "Summerville personal injury cases Frost Law Group handles include car, truck, rideshare, motorcycle, dog bite, fall and wrongful death claims. Call to talk.",
}
T = {"home": "Summerville Personal Injury Attorneys | Call Us First",
     "moto-helmet": "Motorcycle Helmet Law Injury Lawyers in Summerville",
     "dog-strict": "Dog Bite Strict Liability Lawyers in Summerville | Call Us"}
for k,v in D.items(): print(len(v), k)
