# -*- coding: utf-8 -*-
"""Page Manifest v7 additions (2026-09-28): two parents, one car child, eight city pages, nineteen answer pages.
Called from plan.py before plan.json is written. Research: R4 (cities), R5 (answer pages, pedestrian, distracted,
catastrophic), plus R1 to R3 and the county pack."""

OUT_V2 = {
 "act40": ("https://www.scstatehouse.gov/sess126_2025-2026/bills/3276.htm", "2025 Act No. 40, Hands-Free and Distracted Driving Act, enrolled text"),
 "t56c009": ("https://www.scstatehouse.gov/code/t56c009.php", "56-9-330 report copies, 56-9-350 FR-10"),
 "t38c071": ("https://www.scstatehouse.gov/code/t38c071.php", "38-71-190 health insurer subrogation"),
 "t15c050": ("https://www.scstatehouse.gov/code/t15c050.php", "Structured Settlement Protection Act"),
 "fairchild": ("https://www.sccourts.org/media/opinions/HTMLFiles/SC/27112.htm", "Fairchild v. SCDOT, negligence per se, following too closely"),
 "schulmeyer": ("https://www.sccourts.org/media/opinions/HTMLFiles/SC/25612.htm", "Schulmeyer v. State Farm, first-party diminished value"),
 "carter": ("https://www.sccourts.org/media/opinions/HTMLFiles/SC/27340.pdf", "Carter v. Standard Fire, UIM follows a Class I insured on foot"),
 "montgomery": ("https://www.supremecourt.gov/opinions/25pdf/24-1238_1b7d.pdf", "Montgomery v. Caribe Transport II, broker negligent-selection claims not preempted"),
 "msp": ("https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title42-section1395y&num=0&edition=prelim", "Medicare Secondary Payer, 42 USC 1395y(b)"),
 "graves": ("https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title49-section30106&num=0&edition=prelim", "Graves Amendment, 49 USC 30106"),
 "fr309": ("https://dmv.sc.gov/sites/scdmv/files/media/Forms/fr-309.pdf", "SCDMV FR-309, no officer investigated, $1,000, 15 days"),
 "doi_faq": ("https://doi.sc.gov/982/FAQ-Auto-Insurance", "DOI auto FAQ, loss of use, repair shop, total loss"),
 "rfa_caps": ("https://rfa.sc.gov/resources/inflation-adjustments-legal-proceedings", "RFA annual punitive and med-mal cap adjustments"),
 "courts_municipal": ("https://www.sccourts.org/courts/trial-courts/municipal-court/", "Municipal courts have no civil jurisdiction"),
 "courts_berkeley": ("https://www.sccourts.org/courts/courthouse-search/berkeley/", "Berkeley courthouse, 9th Circuit, Goose Creek and Moncks Corner courts"),
 "courts_charleston": ("https://www.sccourts.org/courts/courthouse-search/charleston/", "Charleston courthouse, 9th Circuit, municipal courts, magistrates"),
 "courts_colleton": ("https://www.sccourts.org/courts/courthouse-search/colleton/", "Colleton courthouse, 14th Circuit, Walterboro Municipal Court"),
 "mcpd_records": ("https://monckscornersc.gov/government/police-department/records", "Moncks Corner PD records, $10 report"),
 "cpd_faq": ("https://www.charleston-sc.gov/m/faq?cat=17", "Charleston PD report copies, $5, Records Office"),
 "cpd_patrol": ("https://www.charleston-sc.gov/313/Patrol-Division", "Charleston PD patrol teams incl West Ashley"),
 "ncpd": ("https://police.northcharleston.org/", "North Charleston PD"),
 "mppd_traffic": ("https://www.tompsc.com/186/Traffic-Bureau", "Mount Pleasant PD Traffic Bureau"),
 "walterboro_court": ("https://www.walterborosc.org/court", "Walterboro Municipal Court"),
 "colleton_sheriff": ("https://www.colletoncounty.org/sheriffs-office", "Colleton Sheriff address and records"),
 "scdot_berkeley_aadt": ("https://www.scdot.org/content/dam/scdot-legacy/travel/pdf/trafficcounts/2024/BERKELEY.pdf", "SCDOT 2024 Berkeley traffic counts"),
 "scdot_charleston_aadt": ("https://www.scdot.org/content/dam/scdot-legacy/travel/pdf/trafficcounts/2024/CHARLESTON.pdf", "SCDOT 2024 Charleston traffic counts"),
 "scdot_colleton_aadt": ("https://www.scdot.org/content/dam/scdot-legacy/travel/pdf/trafficcounts/2024/COLLETON.pdf", "SCDOT 2024 Colleton traffic counts"),
 "ravenel": ("https://www.scdot.org/inside/SCDOTPress/2024/Post3532.html", "SCDOT press, Ravenel Bridge on US 17"),
 "muschealth": ("https://muschealth.org/patients-visitors/medical-centers/charleston", "MUSC Medical Center, Level I"),
 "trident": ("https://www.tridenthealthsystem.com/locations/trident-hospital", "Trident Hospital, Level II"),
}


def add_v2(PAGES, pg, U, P, C, HOME, PA, LOC, CONTACT, ABOUT, OUT):
    OUT.update(OUT_V2)
    PAGES[:] = [p for p in PAGES if p["id"] != "car-cat"]  # promoted into the Catastrophic Injury parent
    A = lambda slug: U(P["car"] + slug + "/")

    # ------------------------------------------------------------ two new practice parents
    def parent(id, key, h1, target, title, desc, device, h2, links, outbound, local, replaces, notes=""):
        PAGES.append(pg(id=id, phase="V2", type="Practice area parent page", h1=h1, url=U(P[key]), slug=P[key],
          parent="none, root page", wp_title=h1, kp=h1, words=(5040, 6000), target=target,
          replaces=replaces[0], redirect_from=replaces[1], title=title, desc=desc, device=device, h2=h2,
          first_link=(HOME, "'Frost Law Group' pointing to the homepage"), links=links, outbound=outbound,
          local=local, images="parent", notes=notes))

    parent("cat", "cat", "Catastrophic Injury Attorneys in Summerville", 5250,
     "Catastrophic Injury Attorneys in Summerville | Call Us",
     "Catastrophic Injury Attorneys in Summerville at Frost Law Group document future care, lost earning capacity and coverage after a serious injury. Call today.",
     "The decades after discharge. The page follows a catastrophic injury forward in time, from trauma care through rehabilitation, home changes, the working years and later life, and shows what each stage adds to the claim and how it is proved. Build from llg/v2/retired/car-cat.html (the fixed car child, 3,600 words), widen it beyond car crashes to trucks, motorcycles, falls and dog attacks, and add the R5 section 3 law.",
     ["What Catastrophic Injury Attorneys in Summerville Mean by a Life-Changing Injury",
      "Traumatic Brain Injury Claims a Summerville Serious Injury Lawyer Builds",
      "Spinal Cord Injury and Paralysis Cases a Summerville Catastrophic Injury Lawyer Handles",
      "Amputation, Burn and Scarring Claims Summerville Injury Attorneys Take On",
      "How a Summerville Severe Injury Attorney Proves Future Care and Lost Earning Capacity",
      "Medicaid, Medicare and Health Plan Repayment a Summerville Injury Lawyer Resolves",
      "Policy Limits, Punitive Damages and Deadlines a Summerville Catastrophic Injury Attorney Weighs",
      "Talk With Catastrophic Injury Attorneys in Summerville About the Years Ahead"],
     [HOME, U(P["car"]), U(P["truck"]), U(P["moto"]), U(P["wd"]), U(P["car"] + "drunk-driving-accident-lawyers-in-summerville/"), A("how-much-is-my-car-accident-case-worth"), CONTACT],
     ["t43c007", "dph_trauma"], ["L8", "L6", "L15 serious injury"],
     ("Replaces /practice-areas/catastrophic-injuries", ["/practice-areas/catastrophic-injuries", "/catastrophic-injuries"]),
     "Never use the words expert, specialist or certified. Say life care planner, vocational rehabilitation counselor, economist, treating physician. The only noneconomic damages cap in SC is medical malpractice (15-32-220). Never write 'South Carolina has no caps'. Medicaid recovery is assignment and subrogation (43-7-420 to 440), not a lien. Medicare Secondary Payer: say only what 42 USC 1395y(b) says. Health insurer subrogation per 38-71-190 (limited to what it paid, the Director can disallow it as inequitable, pro rata fees). Punitive cap 15-32-530, the 2026 inflation figure is $739,245 per the RFA memo, which takes effect on State Register publication, not confirmed, so say 'adjusted each year' unless you hedge the figure. Structured Settlement Protection Act governs later sales of payments only. Hospital lien statute is NOT verified, do not mention one. 4.8 star Google rating allowed once, as client reviews on Google.")

    parent("ped", "ped", "Pedestrian Accident Attorneys in Summerville", 5200,
     "Pedestrian Accident Attorneys in Summerville | Call Us",
     "Pedestrian Accident Attorneys in Summerville at Frost Law Group explain crosswalk rules, driver duties and whose insurance pays after a walker is hit. Call.",
     "The crossing itself. Each section starts from where the person on foot was when the car hit them (a signal-controlled crosswalk, an unmarked crossing, a road with no sidewalk, a parking lot, a bike lane) and names the rule that decides fault there, then turns to insurance and to families after a death.",
     ["How Pedestrian Accident Attorneys in Summerville Prove a Driver Failed to Yield",
      "Crosswalk Rules a Summerville Pedestrian Injury Lawyer Applies Under Section 56-5-3130",
      "Walking Where There Is No Sidewalk and How a Summerville Crash Lawyer Weighs Fault",
      "Bicycle Crashes a Summerville Pedestrian and Cyclist Injury Attorney Handles",
      "Whose Insurance Pays When a Summerville Pedestrian Accident Lawyer Opens the Claim",
      "Night Crashes, Children and Older Walkers in the Pedestrian Data a Summerville Lawyer Reviews",
      "Fatal Pedestrian Crashes and the Family Claims Summerville Injury Attorneys Bring",
      "Call Pedestrian Accident Attorneys in Summerville Before You Talk to an Insurer"],
     [HOME, U(P["car"]), U(P["wd"]), U(P["ride"]), A("uninsured-motorist-coverage-in-south-carolina"), U(P["cat"]), CONTACT],
     ["t56c005", "factbook_pdf"], ["L15 pedestrians", "L9", "L10"],
     ("Replaces /practice-areas/pedestrian-accidents (first build) and /pedestrian-accident/ (old site)", ["/practice-areas/pedestrian-accidents", "/pedestrian-accident"]),
     "R5 section 1 governs every legal statement. Crosswalk right-of-way is conditional: a driver yields to a pedestrian in a crosswalk only where traffic-control signals are absent or not working, and the rule turns on which half of the roadway the pedestrian is on (56-5-3130). Crossing outside a crosswalk, sidewalk use and the drivers' due care duty (56-5-3230) as R5 records them. The bicycle statute sets no numeric passing distance, never state one. UM and UIM follow a Class I insured on foot (38-77-30(7), Carter v. Standard Fire 2013). Med pay on foot depends on the policy. Use the 2024 Fact Book pedestrian and bicyclist figures from R5 exactly as labeled. Never say insurers will cite the 146 pedestrian-factor fatal collisions, say officers recorded a pedestrian or cyclist factor as primary in 146 fatal collisions, if you use it at all. 4.8 star Google rating allowed once.")

    # ------------------------------------------------------------ new car child
    PAGES.append(pg(id="car-distracted", phase="V2", type="Practice area child page", h1="Distracted Driving Accident Lawyers in Summerville",
      url=U(P["car"] + "distracted-driving-accident-lawyers-in-summerville/"), slug=P["car"] + "distracted-driving-accident-lawyers-in-summerville/",
      parent=U(P["car"]), wp_title="Distracted Driving Accident Lawyers in Summerville", kp="Distracted Driving Accident Lawyers in Summerville",
      words=(3040, 3700), target=3200, replaces="New page", redirect_from=["/practice-areas/car-accidents/distracted-driving-accidents"],
      title="Distracted Driving Accident Lawyers in Summerville | Call",
      desc="Distracted Driving Accident Lawyers in Summerville at Frost Law Group explain the 2025 hands-free law and how phone use is proved after a crash. Call us today.",
      device="Before and after September 1, 2025. The hands-free law changed what a driver may do with a phone, so each section sets the evidence of distraction against the old texting ban and the new hands-free rule, then shows how it is proved in a claim.",
      h2=["How Distracted Driving Accident Lawyers in Summerville Use the Hands-Free Law",
          "What Section 56-5-3890 Bans and Allows for a Summerville Texting Crash Attorney",
          "Proving Phone Use After a Wreck With a Summerville Distracted Driver Lawyer",
          "Distraction in the Collision Report and the Fact Book a Summerville Car Wreck Lawyer Reads",
          "Work Drivers, Rideshare Drivers and Teen Drivers in Summerville Distraction Claims a Lawyer Reviews",
          "Talk With Distracted Driving Accident Lawyers in Summerville About Your Crash"],
      first_link=(U(P["car"]), "'Frost Law Group' pointing to this page's parent"),
      links=[U(P["car"]), U(P["car"] + "drunk-driving-accident-lawyers-in-summerville/"), U(P["car"] + "hit-and-run-accident-lawyers-in-summerville/"), U(P["ride"]), A("should-i-talk-to-the-other-drivers-insurance-company"), CONTACT],
      outbound=["act40", "factbook_pdf"], local=["L9", "L10", "L15"], images="child",
      notes="R5 section 2 governs. 56-5-3890 as rewritten by 2025 Act No. 40: bans holding or supporting a phone while driving, with the exemptions R5 lists; effective September 1, 2025; warnings only for 180 days; fines $100 then $200 plus 2 points (56-1-720); officers may not search or view the phone for this offense. SC treats violating an applicable statute as negligence per se (Fairchild v. SCDOT, 2012), causation usually a jury question, and no case yet applies it to the hands-free law, so hedge. 56-5-6160 bars evidence of a traffic conviction in a civil case, so never say paying the ticket proves fault. No phone-record subpoena promises, say a lawyer can seek records through the court process when a case is filed. Fact Book distraction figures exactly as R5 labels them."))

    # ------------------------------------------------------------ city pages (county children)
    def city(id, ckey, h1, target, title, desc, device, h2, links, outbound, notes):
        slug = h1.lower().replace(" ", "-")
        PAGES.append(pg(id=id, phase="V2", type="City page (county child)", h1=h1, url=U(C[ckey] + slug + "/"), slug=C[ckey] + slug + "/",
          parent=U(C[ckey]), wp_title=h1, kp=h1, words=(3040, 3700), target=target, replaces="New page", redirect_from=[],
          title=title, desc=desc, device=device, h2=h2, first_link=(U(C[ckey]), "'Frost Law Group' pointing to this page's county parent"),
          links=links, outbound=outbound, local=[f"R4 section for {h1.split(' Car')[0].split(' Personal')[0]}", "R4 section 0 shared facts"], images="child",
          notes=notes + " R4 governs every local fact, and its TRAPS for this city are binding. Municipal courts have no civil jurisdiction (SC Courts). SCDPS publishes no municipal collision totals, so never write 'X crashes in <city>', write that the police department investigated X collisions in 2024 per the Fact Book agency table. County-level Fact Book figures are county figures, never city figures. Never say where EMS will take a patient, never give distances or drive times. The 4.8 star rating is NOT allowed on this page."))

    city("city-goose-creek", "berkeley", "Goose Creek Car Accident Lawyers", 3200,
     "Goose Creek Car Accident Lawyers | Call Frost First",
     "Goose Creek Car Accident Lawyers at Frost Law Group explain who investigates a wreck in the city and how a claim is built in Berkeley County. Call us today.",
     "The route of a Goose Creek crash claim. The page follows one wreck from the roadside (which agency writes the report), through the report office and the insurance claim, to the Berkeley County courthouse, with the city's own roads and agencies at each step.",
     ["How Goose Creek Car Accident Lawyers Get the Collision Report From the Right Agency",
      "US 52, US 176 and Red Bank Road Wrecks a Goose Creek Auto Accident Attorney Reviews",
      "Crashes Near Joint Base Charleston-Weapons Station and the Goose Creek Injury Lawyer's Questions",
      "Uninsured and Hit and Run Drivers a Goose Creek Car Crash Attorney Encounters",
      "Where a Goose Creek Car Wreck Lawyer Files Suit in Berkeley County",
      "Talk With Goose Creek Car Accident Lawyers at Frost Law Group"],
     [U(C["berkeley"]), U(C["berkeley"] + "car-accident-lawyers-in-berkeley-county/"), U(P["car"] + "hit-and-run-accident-lawyers-in-summerville/"), A("uninsured-motorist-coverage-in-south-carolina"), U(C["berkeley"] + "moncks-corner-car-accident-lawyers/"), CONTACT],
     ["courts_municipal", "scdot_berkeley_aadt"],
     "Goose Creek is a city. The police department and municipal court are at 519 North Goose Creek Boulevard. The Goose Creek Magistrate and the Sheriff's South District at 653 Red Bank Road are county offices. Report fees: free in person only for not-at-fault parties and crime victims, $5 for others. The Weapons Station's official name is Joint Base Charleston-Weapons Station, entrance on Red Bank Road per the city. Never say how much of the base is in the city or who investigates crashes on base property. No hospital with a Goose Creek address was verified.")

    city("city-moncks-corner", "berkeley", "Moncks Corner Car Accident Lawyers", 3150,
     "Moncks Corner Car Accident Lawyers | Call Frost First",
     "Moncks Corner Car Accident Lawyers at Frost Law Group explain the report, the insurance claim and the Berkeley County courthouse after a wreck. Call us today.",
     "The county seat. Moncks Corner holds the Berkeley County courthouse and the sheriff's headquarters, so the page is built around the offices a crash claim passes through in the town, set against its growth and its roads.",
     ["How Moncks Corner Car Accident Lawyers Request the Town's Collision Report",
      "US 17A, US 52 and Main Street Crashes a Moncks Corner Auto Accident Attorney Handles",
      "A Growing Town and the Rural Roads Around It for a Moncks Corner Injury Lawyer",
      "Emergency Care and Medical Records a Moncks Corner Car Crash Attorney Collects",
      "The Berkeley County Courthouse in Moncks Corner and Where an Injury Lawyer Files",
      "Speak With Moncks Corner Car Accident Lawyers From Frost Law Group"],
     [U(C["berkeley"]), U(C["berkeley"] + "car-accident-lawyers-in-berkeley-county/"), U(C["berkeley"] + "truck-accident-lawyers-in-berkeley-county/"), U(C["berkeley"] + "goose-creek-car-accident-lawyers/"), U(P["car"]), CONTACT],
     ["mcpd_records", "courts_berkeley"],
     "Moncks Corner is a town and the Berkeley County seat. It grew about 55% since 2020, second among SC towns and cities of 10,000 or more behind Fort Mill, so never call it the fastest growing. Report fee $10 per the town. US 17 ALT is Live Oak Dr per SCDOT, SC 6 is W Main St. Which US 52 segments lie inside the town was not checked, do not place them in town limits. The Moncks Corner freestanding ER is a Trident facility, name it only as R4 does.")

    city("city-charleston", "charleston", "Charleston Personal Injury Lawyers", 3250,
     "Charleston Personal Injury Lawyers | Call Frost First",
     "Charleston Personal Injury Lawyers at Frost Law Group explain crash reports, trauma care and the county courthouse for injury claims in the city. Call today.",
     "The peninsula and beyond. The City of Charleston spans the peninsula, West Ashley, James Island, Johns Island, Daniel Island and a Berkeley County part, so the page is organized by how the city's layout changes who investigates, where care happens and where a case is heard.",
     ["How Charleston Personal Injury Lawyers Work With the City Police Report",
      "Peninsula Streets, I-26 and US 17 Crashes a Charleston Injury Attorney Reviews",
      "Pedestrians, Cyclists and Scooter Riders a Charleston Accident Lawyer Represents",
      "Level I Trauma Care in the City and the Records a Charleston Injury Attorney Gathers",
      "Broad Street and the Charleston County Courthouse for a Charleston Injury Lawyer",
      "Contact Charleston Personal Injury Lawyers at Frost Law Group"],
     [U(C["charleston"]), U(C["charleston"] + "car-accident-lawyers-in-charleston-county/"), U(P["ped"]), U(C["charleston"] + "north-charleston-personal-injury-lawyers/"), U(C["charleston"] + "west-ashley-car-accident-lawyers/"), CONTACT],
     ["cpd_faq", "muschealth"],
     "The City of Charleston is a city, part of it in Berkeley County. Report copies from the Charleston Police Department Records Office, $5 per the city FAQ. MUSC is Adult Level I and the only Pediatric Level I trauma center (DPH). Never say where EMS takes anyone. Charleston County's Court of Common Pleas at 100 Broad Street, Ninth Circuit. The Charleston County Sheriff's Office site was blocked, do not write its address. Keep this page about the city, the county parent covers the county. Moped and scooter facts only as R4 or R3 verify them, otherwise say pedestrians and cyclists.")

    city("city-north-charleston", "charleston", "North Charleston Personal Injury Lawyers", 3250,
     "North Charleston Personal Injury Lawyers | Call Frost First",
     "North Charleston Personal Injury Lawyers at Frost Law Group explain the police report, trauma care and courts after a wreck in the city. Call for a consultation.",
     "One city in three counties. North Charleston sits in Charleston, Dorchester and Berkeley counties, so the page is built around how the county line where a crash happens changes the courthouse and the agencies, with I-26 and I-526 as the spine.",
     ["How North Charleston Personal Injury Lawyers Handle a City Police Crash Report",
      "I-26 and I-526 Interchange Wrecks a North Charleston Injury Attorney Reviews",
      "When a North Charleston Crash Lands in Dorchester or Berkeley County for an Injury Lawyer",
      "Trident and the Emergency Care Records a North Charleston Accident Attorney Collects",
      "Truck Traffic Near the Port Terminals and a North Charleston Personal Injury Attorney",
      "Call North Charleston Personal Injury Lawyers at Frost Law Group"],
     [U(C["charleston"]), U(C["charleston"] + "truck-accident-lawyers-in-charleston-county/"), U(C["dorchester"]), U(C["charleston"] + "charleston-personal-injury-lawyers/"), U(P["truck"]), CONTACT],
     ["ncpd", "trident"],
     "North Charleston is a city, SC's third largest, with about a quarter of residents (32,134) in Dorchester County. Its police only link to a third-party report site (BuyCrash), say reports can be requested online through the service the department links, do not name or link BuyCrash. North Charleston Municipal Court phone (843) 740-2601 is verified but this page shows no phone numbers except the firm's. Trident's own site gives a Charleston 29406 mailing address, the Census places it inside North Charleston, say it sits in North Charleston only in those terms. All five of Charleston County's most crash-prone intersections in 2024 were on I-26 (county level). Port terminal facts only if R4 or R2 verify them, otherwise frame the H2 around commercial truck traffic on I-26 and I-526 generally.")

    city("city-mount-pleasant", "charleston", "Mount Pleasant Car Accident Lawyers", 3150,
     "Mount Pleasant Car Accident Lawyers | Call Frost First",
     "Mount Pleasant Car Accident Lawyers at Frost Law Group explain the town police report, US 17 crashes and where a claim is heard. Call for a free consultation.",
     "The bridge and the bypass. Much of Mount Pleasant's traffic funnels across the Ravenel Bridge and along US 17, so the page follows a wreck on that corridor through the town police, the two nontrauma hospitals and the county courts.",
     ["How Mount Pleasant Car Accident Lawyers Get the Town Police Report",
      "US 17 and Ravenel Bridge Crashes a Mount Pleasant Auto Accident Attorney Reviews",
      "Rear End and Merge Collisions a Mount Pleasant Car Crash Lawyer Sees on Busy Corridors",
      "Emergency Care in the Town and the Records a Mount Pleasant Injury Attorney Needs",
      "Where a Mount Pleasant Car Wreck Lawyer Files Suit in Charleston County",
      "Talk With Mount Pleasant Car Accident Lawyers at Frost Law Group"],
     [U(C["charleston"]), U(C["charleston"] + "car-accident-lawyers-in-charleston-county/"), A("who-is-at-fault-in-a-rear-end-collision"), U(C["charleston"] + "charleston-personal-injury-lawyers/"), U(P["car"]), CONTACT],
     ["mppd_traffic", "ravenel"],
     "Mount Pleasant is a town. SCDOT labels US 17 there 'N HIGHWAY 17', Johnnie Dodds Blvd appears only as S-2474, never pair US 17 with Johnnie Dodds. Neither Mount Pleasant hospital is a trauma center (DPH), name them as R4 does. MPPD street address and report procedure were NOT verified, say the town police department takes reports inside town limits and link the Traffic Bureau page. US-17 had 1,805 collisions in Charleston County in 2024 (county level, not town).")

    city("city-west-ashley", "charleston", "West Ashley Car Accident Lawyers", 3100,
     "West Ashley Car Accident Lawyers | Call Frost First",
     "West Ashley Car Accident Lawyers at Frost Law Group explain who investigates a wreck, where care happens and where a claim is filed. Call for a consultation.",
     "Inside the city or outside it. West Ashley is a district of the City of Charleston with unincorporated county pockets, so the page is organized around how a crash address decides whether city police or another agency writes the report, then follows the claim to the courthouse.",
     ["How West Ashley Car Accident Lawyers Sort Out Who Wrote the Crash Report",
      "US 17, SC 61 and Sam Rittenberg Boulevard Wrecks a West Ashley Auto Attorney Reviews",
      "Unincorporated Pockets and the Agency Questions a West Ashley Injury Lawyer Asks",
      "Medical Care and Records After a West Ashley Crash for Your Car Wreck Attorney",
      "Where a West Ashley Car Crash Lawyer Files an Injury Suit",
      "Speak With West Ashley Car Accident Lawyers From Frost Law Group"],
     [U(C["charleston"]), U(C["charleston"] + "charleston-personal-injury-lawyers/"), U(C["charleston"] + "car-accident-lawyers-in-charleston-county/"), U(P["car"]), A("how-to-get-a-south-carolina-accident-report"), CONTACT],
     ["cpd_patrol", "scdot_charleston_aadt"],
     "West Ashley is an area of the City of Charleston, not a municipality, and it has unincorporated county pockets. There is no Census population for West Ashley, write none. SCDOT's name for US 17 there contains a banned word, always write 'US 17'. Road names only as R4 lists them from SCDOT. Sam Rittenberg Boulevard only if R4 lists it, otherwise rename the H2 to roads R4 verifies (use set_h2.py). Charleston PD Patrol Team 4 covers West Ashley per the city page.")

    city("city-ladson", "berkeley", "Ladson Car Accident Lawyers", 3100,
     "Ladson Car Accident Lawyers | Call Frost First",
     "Ladson Car Accident Lawyers at Frost Law Group explain which county a Ladson wreck falls in, who writes the report and where a claim is heard. Call us today.",
     "Which county, which agency. Ladson is an unincorporated community split between Berkeley and Charleston counties, and its ZIP code reaches into Dorchester, so the page is built around how the exact crash location decides the agency, the report office and the courthouse.",
     ["How Ladson Car Accident Lawyers Find Out Which County a Crash Happened In",
      "College Park Road, Ladson Road and I-26 Wrecks a Ladson Auto Accident Attorney Reviews",
      "Sheriff, Highway Patrol or City Police and the Report a Ladson Injury Lawyer Requests",
      "Emergency Care Near Ladson and the Records a Car Crash Attorney Collects",
      "The Courthouse a Ladson Car Wreck Lawyer Uses in Berkeley or Charleston County",
      "Talk With Ladson Car Accident Lawyers at Frost Law Group"],
     [U(C["berkeley"]), U(C["charleston"]), U(C["berkeley"] + "car-accident-lawyers-in-berkeley-county/"), U(C["berkeley"] + "goose-creek-car-accident-lawyers/"), U(C["dorchester"]), CONTACT],
     ["courts_berkeley", "scdot_berkeley_aadt"],
     "Ladson is an unincorporated census-designated place, never a town or city. 2020 Census: 15,550 people, 12,560 in Berkeley County and 2,990 in Charleston County, none in Dorchester. The Ladson ZIP area (29456) reaches Dorchester County. There is no 2025 estimate for Ladson. Ladson Road is S-76 in Charleston County and S-230 in Dorchester County, never SC 642. College Park Road is S-62 in Berkeley. Whether the I-26 College Park Road interchange lies inside the CDP was NOT verified. Both counties are in the Ninth Circuit. Parts near Ladson may be inside North Charleston city limits, say a crash inside a city's limits is usually that city's police case, without naming specific streets as city land.")

    city("city-walterboro", "colleton", "Walterboro Car Accident Lawyers", 3150,
     "Walterboro Car Accident Lawyers | Call Frost First",
     "Walterboro Car Accident Lawyers at Frost Law Group explain I-95 crashes, the city police and highway patrol reports and the Colleton courthouse. Call today.",
     "The interstate town. Most Colleton County crashes are worked by the Highway Patrol and I-95 carries the heaviest traffic, so the page separates an I-95 wreck from a crash on city streets and follows each to its report, its care and the Colleton County courthouse.",
     ["How Walterboro Car Accident Lawyers Get a Highway Patrol or City Police Report",
      "I-95 Interchange Crashes a Walterboro Auto Accident Attorney Reviews",
      "Out of State Drivers and Insurance Questions for a Walterboro Car Crash Lawyer",
      "Colleton Medical Care and the Records a Walterboro Injury Attorney Gathers",
      "The Colleton County Courthouse and Where a Walterboro Car Wreck Lawyer Files",
      "Call Walterboro Car Accident Lawyers From Frost Law Group"],
     [U(C["colleton"]), U(P["truck"]), U(P["car"]), A("how-to-get-a-south-carolina-accident-report"), U(P["car"] + "hit-and-run-accident-lawyers-in-summerville/"), CONTACT],
     ["colleton_sheriff", "courts_colleton"],
     "Walterboro is a city and the Colleton County seat. In 2024 the Highway Patrol investigated 991 of Colleton County's 1,264 collisions and the Sheriff 7 (Fact Book agency table, county level). I-95 in Colleton carried 48,000 to 49,800 vehicles a day (SCDOT 2024). Colleton's five most crash-prone intersections were all I-95 interchanges (county level). I-95 exit numbers were NOT verified, never write an exit number. Walterboro police street address and report procedure were NOT verified. Colleton Medical Center is not a trauma center, name it as R4 does. Out-of-state driver facts: say only what the law supports, for example that South Carolina courts can hear a claim against a nonresident driver for a crash here, and only if R1 or R5 verify the rule, otherwise frame the section as insurance questions without a legal rule.")

    # ------------------------------------------------------------ answer pages
    def answer(id, pkey, h1, title, desc, device, h2, links, outbound, notes, target=1800):
        slug = "".join(ch if ch.isalnum() else "-" for ch in h1.lower().replace("'", "")).strip("-")
        while "--" in slug: slug = slug.replace("--", "-")
        PAGES.append(pg(id=id, phase="V2", type="Answer page", h1=h1, url=U(P[pkey] + slug + "/"), slug=P[pkey] + slug + "/",
          parent=U(P[pkey]), wp_title=h1, kp=h1.lower(), words=(1500, 2200), target=target, replaces="New page", redirect_from=[],
          title=title, desc=desc, device=device, h2=h2, first_link=(U(P[pkey]), "'Frost Law Group' pointing to this page's parent"),
          links=links, outbound=outbound, local=["R3 and R5 as noted"], images="child",
          notes="ANSWER PAGE. The first paragraph of the H1 section answers the question directly in 40 to 60 words, the sentence Google can quote. H2s are the follow-up questions a reader asks next, each answered directly in its first sentence. Every H2 section still names Frost Law Group once. " + notes + " The 4.8 star rating is NOT allowed on this page."))

    CAR = U(P["car"]); TR = U(P["truck"])
    answer("a-what-to-do", "car", "What to Do After a Car Accident in South Carolina",
     "What to Do After a Car Accident in South Carolina | Read",
     "What to do after a car accident in South Carolina, step by step, from the scene to the report and the insurance calls. Frost Law Group explains. Call with questions.",
     "The first 48 hours in order: at the scene, the same day, the next day, the first week.",
     ["What Does South Carolina Law Require at the Scene of a Crash",
      "When Do You Need a Police Report or an FR-309",
      "What Should You Do About Medical Care the Same Day",
      "Who Should You Call and What Should You Avoid Saying",
      "Talk With a Summerville Car Accident Lawyer About the Next Step"],
     [CAR, A("how-to-get-a-south-carolina-accident-report"), A("should-i-talk-to-the-other-drivers-insurance-company"), A("auto-injury-assessment-in-summerville"), CONTACT],
     ["t56c005", "fr309"], "Duties at the scene per 56-5-1210, 1220, 1230 as R5 and R1 record them. Police notice duty 56-5-1260 covers crashes that injure or kill someone. FR-309 within 15 days when no officer investigated a crash with injury, death or $1,000 in apparent damage. FR-10 back to SCDMV within 15 days (56-9-350). No medical advice, say get checked by a medical provider. No promise about outcomes.")
    answer("a-at-fault", "car", "Is South Carolina an At-Fault State",
     "Is South Carolina an At-Fault State | Get the Answer",
     "Is South Carolina an at-fault state? Yes. Frost Law Group explains whose insurance pays after a crash, the minimum limits and how fault is shared. Call with questions.",
     "The answer, then the three consequences: whose policy pays, how much it must carry, and what happens when fault is shared.",
     ["Whose Insurance Pays First After a South Carolina Crash",
      "What Are South Carolina's Minimum Liability Limits",
      "What Happens When Both Drivers Share the Blame",
      "What If the At-Fault Driver Has No Insurance",
      "Ask a Summerville Car Accident Attorney About Fault in Your Crash"],
     [CAR, A("how-comparative-negligence-works-in-south-carolina"), A("uninsured-motorist-coverage-in-south-carolina"), A("south-carolina-car-accident-laws"), CONTACT],
     ["doi_auto", "t38c077"], "At-fault (tort) system per DOI. Minimums 25/50/25 (38-77-140). UM mandatory (38-77-150), UIM offered not required (38-77-160). Med pay optional. Modified comparative negligence: recovery barred if the plaintiff's fault exceeds 50%, reduced by the plaintiff's share.")
    answer("a-comparative", "car", "How Comparative Negligence Works in South Carolina",
     "How Comparative Negligence Works in South Carolina | Read",
     "How comparative negligence works in South Carolina: an award is cut by your share of fault and barred above 50%. Frost Law Group explains with examples. Call us.",
     "Three worked examples at 20%, 50% and 51% fault, then who decides the split and how several defendants share it.",
     ["What Happens at 20%, 50% and 51% Fault",
      "Who Decides How Fault Is Divided",
      "How Does Fault Work With More Than One Driver",
      "Can the Insurer Blame You Before Anyone Decides Fault",
      "Talk With a Summerville Car Accident Lawyer About Shared Fault"],
     [CAR, A("is-south-carolina-an-at-fault-state"), A("who-is-at-fault-in-a-rear-end-collision"), A("what-happens-if-a-car-accident-was-your-fault"), CONTACT],
     ["t15c038", "fairchild"], "Never call it the 51% rule as a headline claim, explain it. The under-50% several-liability rule in 15-38-15(A) dates to July 1, 2005, Act 42 of 2025 added nonparty fault allocation and removed the gross negligence and alcohol exceptions for claims arising after January 1, 2026. The jury decides fault. Examples use round numbers and no dollar predictions for the reader's case.")
    answer("a-sol", "car", "South Carolina Car Accident Statute of Limitations",
     "SC Car Accident Statute of Limitations | Know Your Deadline",
     "The South Carolina car accident statute of limitations is usually three years. Frost Law Group explains the exceptions for minors, deaths and government claims. Call.",
     "The general rule, then each exception in the order a reader needs it: property damage, minors, deaths, government vehicles, and when the clock starts.",
     ["When Does the Three-Year Clock Start",
      "Does a Child Get More Time",
      "What Deadline Applies After a Fatal Crash",
      "What If a Government Vehicle or Road Caused the Crash",
      "Does an Open Insurance Claim Stop the Clock",
      "Call a Summerville Car Accident Attorney Before a Deadline Passes"],
     [CAR, A("how-long-after-a-car-accident-can-you-claim-injury"), U(P["wd"]), A("how-long-does-a-car-accident-case-take"), CONTACT],
     ["t15c003", "t15c078"], "15-3-530 three years, 15-3-535 discovery. 15-3-40 minors: the extension ends no later than one year after the child turns 18 and adds nothing when the ordinary period runs later. Wrongful death three years from death. Tort Claims Act: two years, three only if a verified claim is filed first and received within one year after the loss was or should have been discovered (15-78-80(d), 15-78-110). An open insurance claim does not by itself extend the deadline, say it as R5 supports. Never state a duration for how long a claim takes.", target=1850)
    answer("a-laws", "car", "South Carolina Car Accident Laws",
     "South Carolina Car Accident Laws | What Drivers Should Know",
     "South Carolina car accident laws cover reporting, insurance, seat belts, phones and fault. Frost Law Group explains each rule in plain English. Call with questions.",
     "The laws in the order they touch a crash: the rules of the road, the duty to stop and report, insurance, seat belts and phones, then fault and deadlines.",
     ["Which Rules of the Road Decide Most Crash Claims",
      "What Must a Driver Do After a Crash",
      "What Insurance Must Every South Carolina Driver Carry",
      "How Do the Seat Belt and Hands-Free Laws Affect a Claim",
      "What Deadlines and Fault Rules Apply to a Claim",
      "Ask a Summerville Car Accident Lawyer How These Laws Apply to You"],
     [CAR, A("is-south-carolina-an-at-fault-state"), A("south-carolina-car-accident-statute-of-limitations"), U(P["car"] + "distracted-driving-accident-lawyers-in-summerville/"), CONTACT],
     ["t56c005", "act40"], "Seat belt rule 56-5-6540 exactly as R5 records it, including whether nonuse can be used to reduce damages. Hands-free law 56-5-3890 per R5. 56-5-6160 bars evidence of a traffic conviction in a civil case. Following too closely 56-5-1930, failure to yield sections as R1 records.")
    answer("a-talk-insurer", "car", "Should I Talk to the Other Driver's Insurance Company",
     "Should I Talk to the Other Driver's Insurer | Read First",
     "Should I talk to the other driver's insurance company? Frost Law Group explains recorded statements, medical releases and what to say first. Call with questions today.",
     "What the adjuster wants from each request (a statement, a release, a quick check) and what you owe your own insurer instead.",
     ["Do You Have to Give a Recorded Statement",
      "Should You Sign a Medical Records Release",
      "What Do You Owe Your Own Insurance Company",
      "What About a Quick Settlement Offer",
      "Talk With a Summerville Car Accident Attorney Before You Call Back"],
     [CAR, A("what-to-do-after-a-car-accident-that-was-not-your-fault"), A("how-much-is-my-car-accident-case-worth"), A("what-to-do-after-a-car-accident-in-south-carolina"), CONTACT],
     ["doi_faq", "t38c077"], "No statute requires a claimant to give the other driver's insurer a recorded statement, say only what R5 supports. The cooperation duty to your own insurer comes from the policy, not a statute, say so. A release signed in a settlement usually ends the claim, say it generally without a statute unless R5 has one. No advice to lie or refuse your own insurer.")
    answer("a-um", "car", "Uninsured Motorist Coverage in South Carolina",
     "Uninsured Motorist Coverage in South Carolina | Learn How",
     "Uninsured motorist coverage in South Carolina is required on every auto policy. Frost Law Group explains how UM and UIM pay after a crash. Call with questions.",
     "Two coverages side by side: UM when the other driver has no insurance or cannot be found, UIM when their limits are too low, then stacking and who counts as an insured.",
     ["When Does Uninsured Motorist Coverage Pay",
      "How Is Underinsured Motorist Coverage Different",
      "What If the Driver Who Hit You Drove Away",
      "Can You Stack UM or UIM Coverage",
      "Are You Covered on Foot, on a Bike or in Someone Else's Car",
      "Ask a Summerville Car Accident Lawyer to Read Your Policy"],
     [CAR, U(P["car"] + "hit-and-run-accident-lawyers-in-summerville/"), U(P["moto"] + "uninsured-motorist-motorcycle-lawyers-in-summerville/"), U(P["ped"]), CONTACT],
     ["t38c077", "carter"], "UM mandatory 38-77-150, UIM offered 38-77-160, no UIM consent-to-settle clause allowed (38-77-160). Unknown driver 38-77-170 as rewritten in 2024: physical contact, an independent witness, or a recording, plus a police report within a reasonable time. Stacking and Class I and II per R1 section 7. UM and UIM follow a Class I insured on foot (Carter, 2013).")
    answer("a-assessment", "car", "Auto Injury Assessment in Summerville",
     "Auto Injury Assessment in Summerville | What to Know",
     "An auto injury assessment in Summerville documents injuries after a crash. Frost Law Group explains where to go, what to bring and how bills get paid. Call us.",
     "What an evaluation is for, where people in Summerville get one, what to tell the provider, and how the bills are paid while the claim is open.",
     ["Why Get Checked Even If You Feel Fine",
      "Where Can You Be Evaluated in and Around Summerville",
      "What Should You Tell the Provider About the Crash",
      "Who Pays the Medical Bills While a Claim Is Open",
      "Talk With a Summerville Car Accident Attorney About Your Records"],
     [CAR, A("how-long-after-a-car-accident-can-you-claim-injury"), A("what-to-do-after-a-car-accident-in-south-carolina"), U(P["cat"]), CONTACT],
     ["dph_trauma", "t38c071"], "No medical advice and no provider recommendations or endorsements. Name only facilities R3 or R4 verify (HCA Healthcare Summerville Hospital at 295 Midland Pkwy is inside the Town of Summerville per R4, Roper St. Francis Berkeley Hospital is in Berkeley County), never say where EMS takes anyone, no distances. Med pay per R1 section 8. Health insurer subrogation per 38-71-190 as R5 records. Never say an assessment 'proves' injury.")
    answer("a-where", "car", "Where Car Accidents Happen in Summerville",
     "Where Car Accidents Happen in Summerville | See the Data",
     "Where car accidents happen in Summerville, from Dorchester Road to I-26, by the 2024 crash data. Frost Law Group explains what the location means for a claim. Call.",
     "The roads and intersections in the 2024 Fact Book and SCDOT counts, then who investigates each and what the location changes about a claim.",
     ["Which Roads Near Summerville Had the Most Crashes in 2024",
      "Which Intersections Had the Most Collisions",
      "Who Investigates a Crash on Each Road",
      "What Does the Crash Location Change About a Claim",
      "Ask a Summerville Car Accident Lawyer About a Crash on Your Route"],
     [CAR, U(C["dorchester"]), A("how-to-get-a-south-carolina-accident-report"), U(C["berkeley"] + "car-accident-lawyers-in-berkeley-county/"), CONTACT],
     ["factbooks", "scdot_dorchester_aadt"], "Use only R3 facts: Dorchester Road (SC 642) 519 collisions and 6 deaths in Dorchester County in 2024; Dorchester Road at Old Trolley Road 53, at Ladson Road 49, at Bacons Bridge Road 41; US-78 at SC-165 56 (never call that junction Bacons Bridge Road); SCDOT AADT figures as R3 lists. Summerville is in three counties. Agency figures per R3 L16. County figures are county figures.")
    answer("a-report", "car", "How to Get a South Carolina Accident Report",
     "How to Get a South Carolina Accident Report | Step by Step",
     "How to get a South Carolina accident report from SCDMV or the police, what it costs and what to do if it is wrong. Frost Law Group explains. Call with questions.",
     "Which form is which (FR-10, TR-310, FR-50, FR-309), then where each comes from and what to do about an error.",
     ["What Is the Difference Between an FR-10 and a TR-310",
      "How Do You Request a Report From SCDMV",
      "Can You Get the Report From the Police Agency Instead",
      "What If the Report Has a Mistake",
      "Talk With a Summerville Car Accident Attorney About Your Report"],
     [CAR, A("can-you-claim-a-car-accident-without-a-police-report"), A("what-to-do-after-a-car-accident-in-south-carolina"), U(C["berkeley"] + "goose-creek-car-accident-lawyers/"), CONTACT],
     ["dmv_reports", "t56c009"], "SCDMV FR-50, $10, per R3 and R5. TR-310 via SCDMV per the SCHP FAQ. FR-10 returned within 15 days (56-9-350). Local agency procedures only as R3 and R4 verify (Summerville PD page, Goose Creek $5 or free for not-at-fault parties in person, Moncks Corner $10, Charleston PD $5). Reports under 56-5-1260 to 1280 are not evidence of negligence at a damages trial (56-5-1290) as R1 records. Say an officer can be asked to review a report, no promise it changes.")
    answer("a-no-report", "car", "Can You Claim a Car Accident Without a Police Report",
     "Can You Claim a Car Accident Without a Police Report | Read",
     "Can you claim a car accident without a police report in South Carolina? Often yes. Frost Law Group explains the FR-309 and the proof a claim needs. Call with questions.",
     "Yes, then what replaces the report as proof, the FR-309 duty, and the one situation where a report is required for coverage (the unknown driver).",
     ["What Takes the Place of a Police Report as Proof",
      "When Must You File an FR-309 With SCDMV",
      "When Is a Police Report Required for Coverage",
      "Can You Still Report the Crash Later",
      "Ask a Summerville Car Accident Lawyer What Proof You Have"],
     [CAR, A("how-to-get-a-south-carolina-accident-report"), U(P["car"] + "hit-and-run-accident-lawyers-in-summerville/"), A("what-to-do-after-a-minor-car-accident"), CONTACT],
     ["fr309", "t38c077"], "FR-309 within 15 days when no officer investigated a crash with injury, death or $1,000 in apparent damage (56-5-1270). The unknown-driver UM claim needs a police report within a reasonable time (38-77-170). Police notice duty under 56-5-1260 applies to injury or death crashes.")
    answer("a-claim-later", "car", "How Long After a Car Accident Can You Claim Injury",
     "How Long After a Car Accident Can You Claim Injury | Read",
     "How long after a car accident can you claim injury in South Carolina? The legal deadline and the practical one differ. Frost Law Group explains. Call with questions.",
     "Two clocks: the legal deadline and the practical one set by medical records and policy notice terms.",
     ["What Is the Legal Deadline to Claim an Injury",
      "Why Does a Gap in Treatment Matter",
      "What About Injuries That Show Up Days Later",
      "Do Insurance Policies Have Their Own Notice Deadlines",
      "Talk With a Summerville Car Accident Attorney About a Late Injury"],
     [CAR, A("south-carolina-car-accident-statute-of-limitations"), A("auto-injury-assessment-in-summerville"), A("how-much-is-my-car-accident-case-worth"), CONTACT],
     ["t15c003", "doi_faq"], "Legal deadlines per 15-3-530, 15-3-535, 15-3-40 and the Tort Claims Act (full rule). Policy notice terms come from the policy, not a statute, say so. No medical advice. No durations for claims.")
    answer("a-not-fault", "car", "What to Do After a Car Accident That Was Not Your Fault",
     "After a Car Accident That Was Not Your Fault | Read This",
     "What to do after a car accident that was not your fault in South Carolina: the property claim, the rental and total loss. Frost Law Group explains. Call with questions.",
     "The property side first (repairs, rental, total loss), then the injury side, then what not to sign.",
     ["Whose Insurer Pays for Your Car and Rental",
      "What Happens If Your Car Is a Total Loss",
      "Can You Claim Diminished Value in South Carolina",
      "What Should You Not Sign Early",
      "Ask a Summerville Car Accident Lawyer About the Claim Ahead"],
     [CAR, A("should-i-talk-to-the-other-drivers-insurance-company"), A("how-much-is-my-car-accident-case-worth"), A("what-to-do-after-a-car-accident-in-south-carolina"), CONTACT],
     ["doi_faq", "schulmeyer"], "Vehicle damage measure: market value before and after plus loss of use (Newman v. Brown, 1955, do not link CourtListener). Schulmeyer (2003) denies diminished value under one first-party policy form. No SC case squarely allows third-party diminished value, so say it is unsettled and depends on the facts. No statute on total-loss valuation, DOI guidance covers loss of use and actual cash value, the 75% figure is a salvage-title rule only. Repair shop choice per DOI FAQ.")
    answer("a-minor", "car", "What to Do After a Minor Car Accident",
     "What to Do After a Minor Car Accident | Read the Steps",
     "What to do after a minor car accident in South Carolina, from moving the cars to reporting and the claim. Frost Law Group explains when a lawyer helps. Call us.",
     "A fender bender in order: move safely, exchange information, decide on reporting, handle the property claim, then watch for delayed injury.",
     ["Do You Have to Call the Police After a Minor Crash",
      "What Information Should You Exchange",
      "Can You Handle a Small Property Claim Yourself",
      "When Is a Minor Crash Not So Minor",
      "Talk With a Summerville Car Accident Attorney If Symptoms Appear"],
     [CAR, A("can-you-claim-a-car-accident-without-a-police-report"), A("what-to-do-after-a-car-accident-that-was-not-your-fault"), A("auto-injury-assessment-in-summerville"), CONTACT],
     ["t56c005", "fr309"], "Police notice duty only for injury or death (56-5-1260). FR-309 for $1,000 apparent damage when no officer investigated. Exchange of information 56-5-1230 as R5 records. It is fine to say a person with no injury may handle a small property claim without a lawyer.")
    answer("a-my-fault", "car", "What Happens If a Car Accident Was Your Fault",
     "What Happens If a Car Accident Was Your Fault | Read",
     "What happens if a car accident was your fault in South Carolina? Your liability coverage answers, and you may still recover. Frost Law Group explains. Call us.",
     "Your coverage first (liability, defense), then your own injuries (med pay, shared fault), then what to avoid saying.",
     ["Does Your Liability Insurance Pay the Other Driver",
      "What If You Are Sued",
      "Can You Still Recover for Your Own Injuries",
      "Should You Admit Fault at the Scene",
      "Ask a Summerville Car Accident Lawyer About Your Own Injuries"],
     [CAR, A("how-comparative-negligence-works-in-south-carolina"), A("is-south-carolina-an-at-fault-state"), A("should-i-talk-to-the-other-drivers-insurance-company"), CONTACT],
     ["t38c077", "t15c038"], "Never steer the reader to criminal defense or the main site. Liability coverage and the insurer's defense come from the policy, say so. Shared fault per comparative negligence. 56-5-6160 bars traffic-conviction evidence in a civil case. No advice to hide facts.")
    answer("a-rear-end", "car", "Who Is at Fault in a Rear End Collision",
     "Who Is at Fault in a Rear End Collision | Read the Rules",
     "Who is at fault in a rear end collision in South Carolina? Usually the trailing driver, but not always. Frost Law Group explains the rules and defenses. Call us.",
     "The usual answer, the rule behind it, then the three situations that change it (a sudden stop, a cut-in, a chain reaction).",
     ["What Does the Following Too Closely Law Require",
      "Is There a Legal Presumption Against the Rear Driver",
      "Can the Front Driver Share the Blame",
      "Who Is Responsible in a Chain Reaction Crash",
      "Talk With a Summerville Car Accident Attorney About a Rear End Crash"],
     [CAR, A("how-comparative-negligence-works-in-south-carolina"), A("where-car-accidents-happen-in-summerville"), U(C["charleston"] + "mount-pleasant-car-accident-lawyers/"), CONTACT],
     ["fairchild", "t56c005"], "56-5-1930 following too closely. No rear-end presumption was found in SC, the verified position is that a jury may infer following too closely from a rear-end crash (R5), say exactly that. Fairchild v. SCDOT: violating an applicable statute is negligence per se, causation usually a jury question. Act 42 and 15-38-15 for chain reactions per item A (the under-50% rule dates to 2005).")
    answer("a-worth", "car", "How Much Is My Car Accident Case Worth",
     "How Much Is My Car Accident Case Worth | Learn the Factors",
     "How much is my car accident case worth in South Carolina? It depends on damages, fault and coverage. Frost Law Group explains each factor. Call with questions today.",
     "The factors in the order they set a value: the damages, then fault, then the insurance available, then repayment of bills, with why averages mislead.",
     ["What Damages Make Up a Car Accident Claim",
      "How Does Fault Change the Number",
      "Why Do Policy Limits Matter So Much",
      "Who Gets Repaid From a Settlement",
      "Why Online Settlement Averages Mislead",
      "Ask a Summerville Car Accident Lawyer What Drives Value in Your Case"],
     [CAR, A("how-comparative-negligence-works-in-south-carolina"), A("uninsured-motorist-coverage-in-south-carolina"), U(P["cat"]), CONTACT],
     ["t38c077", "t43c007"], "Never give a value, a range, an average or a multiplier. No 'studies show' claims. Punitive damages only with the 15-32-520 clear and convincing standard and the 15-32-530 cap as adjusted each year. Medicaid and health plan repayment per R5. No case results.")
    answer("a-how-long", "car", "How Long Does a Car Accident Case Take",
     "How Long Does a Car Accident Case Take | What to Expect",
     "How long does a car accident case take in South Carolina? It depends on treatment, coverage and whether suit is filed. Frost Law Group explains the stages. Call us.",
     "The stages in order (treatment, demand, negotiation, suit, discovery, mediation, trial) with what decides the pace of each, and no promised durations.",
     ["What Happens Before a Demand Is Sent",
      "What Slows a Claim Down",
      "What Changes If a Lawsuit Is Filed",
      "Does Every Case Go to Trial",
      "Talk With a Summerville Car Accident Attorney About Your Timeline"],
     [CAR, A("south-carolina-car-accident-statute-of-limitations"), A("how-much-is-my-car-accident-case-worth"), U(C["dorchester"]), CONTACT],
     ["t15c003", "courts_circuit"], "Never state how many weeks or months any stage takes. Statutory deadlines are fine. Mediation requirements only if R3 or R5 verify them for these counties, otherwise say many civil cases go to mediation. Court of Common Pleas per R3.")
    answer("a-truck-liable", "truck", "Who Is Liable in a Truck Accident",
     "Who Is Liable in a Truck Accident | Learn Who Pays",
     "Who is liable in a truck accident in South Carolina? The driver, the carrier, the owner, a broker or a shipper may share it. Frost Law Group explains. Call us today.",
     "Each party in the order a claim reaches it (driver, motor carrier, owner or lessor, broker, shipper and loader, maintenance shop) with the rule that can make it answer.",
     ["When Is the Motor Carrier Responsible for Its Driver",
      "Can the Truck's Owner or Leasing Company Be Liable",
      "Can a Freight Broker Be Sued After a Crash",
      "What About the Shipper, the Loader or the Repair Shop",
      "How Is Fault Divided Among Several Trucking Defendants",
      "Talk With a Summerville Truck Accident Attorney About Every Party"],
     [TR, U(P["truck"] + "tractor-trailer-accident-lawyers-in-summerville/"), U(P["truck"] + "truck-driver-fatigue-accident-lawyers-in-summerville/"), U(P["wd"] + "fatal-truck-accident-lawyers-in-summerville/"), CONTACT],
     ["montgomery", "graves"], "R2 section A and R5 section 5 govern. Leasing: 49 CFR 376.12 gives the carrier exclusive control but says it does not decide contractor status. Graves Amendment 49 USC 30106 protects rental and leasing owners absent their own negligence. Montgomery v. Caribe Transport II (May 14, 2026) held broker negligent-selection claims are not preempted by the FAAAA safety exception, it does not make a broker liable, SC negligent selection law was not researched, and the Court left the intrastate provision open. Say all three limits. Loading: the Savage rule is a Fourth Circuit 1953 case, not confirmed as SC law, hedge or omit. Joint and several per item A.", target=1900)


def link_targets():
    return OUT_V2
