# -*- coding: utf-8 -*-
"""Master plan for the Frost Law Group personal injury page build, 2026-09-28.
Single source of truth for URLs, keyphrases, metadata, devices, H2 plans, links and outbound sources.
Controlling references: Page Manifest v6 (2026-09-15), project instructions section 15, llg-website-build."""
import json, os

BASE = "https://www.summervilleaccidentattorney.com"
def U(path): return BASE + path

HOME = U("/"); PA = U("/practice-areas"); LOC = U("/locations/"); CONTACT = U("/contact"); ABOUT = U("/about")
P = {  # practice parents
 "car": "/car-accident-attorneys-in-summerville/",
 "truck": "/truck-accident-attorneys-in-summerville/",
 "moto": "/motorcycle-accident-attorneys-in-summerville/",
 "ride": "/rideshare-accident-attorneys-in-summerville/",
 "slip": "/slip-and-fall-attorneys-in-summerville/",
 "dog": "/dog-bite-attorneys-in-summerville/",
 "wd": "/wrongful-death-attorneys-in-summerville/",
 "cat": "/catastrophic-injury-attorneys-in-summerville/",
 "ped": "/pedestrian-accident-attorneys-in-summerville/",
}
C = {k: f"/personal-injury-attorneys-in-{k}-county/" for k in
     ["dorchester","charleston","berkeley","colleton","orangeburg","beaufort","georgetown","williamsburg"]}

OUT = {  # verified outbound sources (direct 200, 2026-09-28)
 "factbooks": ("https://scdps.sc.gov/ohsjp/stat_services/factbooks", "SCDPS Traffic Collision Fact Book listing, 2024 is newest"),
 "factbook_pdf": ("https://scdps.sc.gov/sites/scdps/files/Documents/ohsjp/fact%20book/2024%20Fact%20Book.pdf", "2024 Fact Book PDF"),
 "dmv_reports": ("https://dmv.sc.gov/vehicle-owners/collision-reports", "SCDMV collision report requests, FR-50, $10"),
 "t15c003": ("https://www.scstatehouse.gov/code/t15c003.php", "15-3-530 three-year deadline, 15-3-40 minors"),
 "t56c005": ("https://www.scstatehouse.gov/code/t56c005.php", "Title 56 Ch 5 traffic code, 56-5-1210 hit and run, 1260/1270 reporting, 2320 left turn, 3640-3680 motorcycles, 4100 loads, 4240 intrastate FMCSR, 6540 seat belts"),
 "t38c077": ("https://www.scstatehouse.gov/code/t38c077.php", "Auto insurance: 140 minimums, 150 UM, 160 UIM, 170 unknown driver, 250 limits disclosure, 350 offer forms"),
 "t58c023": ("https://www.scstatehouse.gov/code/t58c023.php", "TNC Act 58-23-1610 to 1720"),
 "t15c038": ("https://www.scstatehouse.gov/code/t15c038.php", "15-38-15 joint and several, Act 42"),
 "t15c032": ("https://www.scstatehouse.gov/code/t15c032.php", "15-32-530 punitive damages cap and exceptions, 15-32-220 med mal cap"),
 "t61c002": ("https://www.scstatehouse.gov/code/t61c002.php", "61-2-145 liquor liability insurance, 61-2-147 DUI tortfeasor verdict form"),
 "t47c003": ("https://www.scstatehouse.gov/code/t47c003.php", "47-3-110 dog bite strict liability, 47-3-710 dangerous animals"),
 "t47c005": ("https://www.scstatehouse.gov/code/t47c005.php", "Rabies Control Act bite reports and quarantine"),
 "t15c051": ("https://www.scstatehouse.gov/code/t15c051.php", "Wrongful Death Act 15-51-10 to 60"),
 "t15c005": ("https://www.scstatehouse.gov/code/t15c005.php", "15-5-90 survival, 15-5-100 funeral expenses"),
 "t62c005": ("https://www.scstatehouse.gov/code/t62c005.php", "62-5-433 minors' settlements"),
 "t62c003": ("https://www.scstatehouse.gov/code/t62c003.php", "Probate appointment of personal representative"),
 "t27c040": ("https://www.scstatehouse.gov/code/t27c040.php", "Residential Landlord and Tenant Act 27-40-440"),
 "t15c078": ("https://www.scstatehouse.gov/code/t15c078.php", "SC Tort Claims Act"),
 "t43c007": ("https://www.scstatehouse.gov/code/t43c007.php", "Medicaid assignment and subrogation 43-7-420 to 440"),
 "t22c003": ("https://www.scstatehouse.gov/code/t22c003.php", "22-3-10 magistrate $7,500 civil limit"),
 "wintersteen": ("https://www.sccourts.org/media/opinions/HTMLFiles/SC/25254.htm", "Wintersteen v. Food Lion, store notice rule"),
 "bass": ("https://www.sccourts.org/media/opinions/HTMLFiles/SC/27054.htm", "Bass v. Gopal, business duty to protect against foreseeable crime"),
 "marcum": ("https://www.sccourts.org/media/opinions/HTMLFiles/SC/26259.htm", "Marcum v. Bowden social host liability, summarizes Tobias"),
 "ecfr_395_3": ("https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-395/subpart-A/section-395.3", "49 CFR 395.3 hours of service"),
 "ecfr_395_8": ("https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-395/subpart-A/section-395.8", "49 CFR 395.8 ELD and record retention"),
 "ecfr_390_5": ("https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-390/subpart-A/section-390.5", "49 CFR 390.5 CMV definition 10,001 lb"),
 "ecfr_387_9": ("https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-387/subpart-A/section-387.9", "49 CFR 387.9 insurance minimums"),
 "ecfr_382_303": ("https://www.ecfr.gov/current/title-49/subtitle-B/chapter-III/subchapter-B/part-382/subpart-C/section-382.303", "49 CFR 382.303 post-accident testing"),
 "ecfr_391_51": ("https://www.ecfr.gov/current/title-49/section-391.51", "49 CFR 391.51 driver qualification files"),
 "dph_trauma": ("https://dph.sc.gov/professionals/healthcare-quality/ems-and-trauma/sc-trauma-system", "SC DPH trauma center list"),
 "dph_rabies": ("https://dph.sc.gov/diseases-conditions/infectious-diseases/animal-borne-diseases/rabies", "SC DPH rabies and bite reporting"),
 "doi_auto": ("https://doi.sc.gov/588/Automobile-Insurance", "SC DOI auto insurance minimums, UM, UIM"),
 "courts_dorchester": ("https://www.sccourts.org/courts/courthouse-search/dorchester/", "Dorchester courthouse, Troy Knight complex, First Circuit"),
 "courts_circuit": ("https://www.sccourts.org/courts/trial-courts/circuit-court/", "Circuit Court and Court of Common Pleas"),
 "courts_probate": ("https://www.sccourts.org/courts/trial-courts/probate-court/", "Probate court jurisdiction incl minor settlements under $25,000"),
 "courts_magistrate": ("https://www.sccourts.org/courts/trial-courts/magistrate-court/", "Magistrate court $7,500 civil limit"),
 "courts_search": ("https://www.sccourts.org/courts/courthouse-search/", "SC Judicial Branch courthouse search"),
 "schp_troop6": ("https://scdps.sc.gov/schp/contact/troop6", "SCHP Troop Six counties and HQ"),
 "schp_troops": ("https://scdps.sc.gov/schp/contact/troops", "SCHP troops, MAIT Troop Nine, FR-10 FAQ"),
 "summerville_pd_reports": ("https://www.summervillepolice.com/533/Obtain-a-Collision-Report", "Summerville PD collision reports"),
 "scdot_dorchester_aadt": ("https://www.scdot.org/content/dam/scdot-legacy/travel/pdf/trafficcounts/2024/DORCHESTER.pdf", "SCDOT 2024 Dorchester traffic counts, route names"),
 "scdot_trafficdata": ("https://www.scdot.org/travel/travel-trafficdata.html", "SCDOT traffic counts landing page"),
 "census_quickfacts_counties": ("https://www.census.gov/quickfacts/", "Census QuickFacts (403 to bots, avoid as link)"),
}

def pg(**k): return k

PAGES = []
# ---------------------------------------------------------------- PHASE A
PAGES.append(pg(id="home", phase="A", type="Home page", h1="Summerville Personal Injury Attorneys", url=HOME, slug="/",
 parent="none, root page (site home)", wp_title="Home", kp="Summerville personal injury attorneys",
 words=(8040, 10000), target=9200, replaces="Rewrite in place of the current homepage", redirect_from=[],
 title="Summerville Personal Injury Attorneys | Call Frost First",
 desc="Summerville personal injury attorneys at Frost Law Group help injured people across eight South Carolina counties. Call for a free, confidential consultation.",
 device="The caller's questions in the order a caller asks them. What kind of case is this, who will handle it, does the firm cover my county, what do I do now. The approved heading tree already follows that order, so every section answers the question a first-time caller is really asking at that point.",
 structure_locked=True,
 h2=["Types of Cases Our Summerville Personal Injury Attorneys Represent",
     "Why Turn to Frost Law After an Accident in Summerville, South Carolina",
     "Counties Where Our Summerville Personal Injury Lawyers Help Clients",
     "Call Frost First When You Need a Summerville Injury Attorney"],
 locked_tree="""H1 Summerville Personal Injury Attorneys
H2 Types of Cases Our Summerville Personal Injury Attorneys Represent
  H3 Motor Vehicle Accident Injuries
    H4 Summerville Car Accident Attorneys            (link car parent)
    H4 Commercial Truck Accident Lawyers in Summerville, South Carolina   (link truck parent)
    H4 Motorcycle Accident Injury Lawyers            (no city modifier, Nick's instruction; link motorcycle parent)
    H4 Ride Share Accident Attorneys                 (link rideshare parent)
      H5 Summerville Uber Accident Lawyers           (link Uber child)
      H5 Lyft Accident Injury Attorneys in Summerville, South Carolina   (link Lyft child)
  H3 Slip and Fall Lawyers                           (link slip and fall parent)
  H3 Dog Bite Attorneys in Summerville, South Carolina   (link dog bite parent)
  H3 Wrongful Death Accident Injury Attorneys in Summerville, South Carolina  (tie wrongful death to motor vehicle crashes, Nick allowed; link wrongful death parent)
H2 Why Turn to Frost Law After an Accident in Summerville, South Carolina
  H3 x4, you write them. Material: Tara's former service as a Dorchester County Magistrate Judge and Associate Probate Judge (courtroom perspective only), Jack's fourteen years with the Summerville Police Department and Charleston County Sheriff's Office (how investigations and reports are built), a family practice where a caller reaches an attorney who lives in Summerville, and the free confidential consultation plus the 4.8 star Google rating. H3 wording must be search-useful, e.g. "Courtroom Perspective From a Former Dorchester County Magistrate Judge". Each H3 needs 3+ sentences, 60+ words. You may add H4s under these only in pairs.
H2 Counties Where Our Summerville Personal Injury Lawyers Help Clients
  H3 x8, one per county in this order: Dorchester, Charleston, Berkeley, Colleton, Orangeburg, Beaufort, Georgetown, Williamsburg. Each H3 links that county's parent page once. Never use the county page H1 string "Personal Injury Attorneys in X County" as the H3. Every H3 wording shape must differ (no formula). About 230 to 280 words each, each with its own distinct local fact from the county pack section 5.
H2 Call Frost First When You Need a Summerville Injury Attorney   (final CTA, no subheadings, built on Frost First)""",
 first_link=(PA, "natural service name such as 'personal injury cases' pointing to the Practice Areas page"),
 links=[PA, U(P["car"]), U(P["truck"]), U(P["moto"]), U(P["ride"]), U(P["ride"]+"uber-accident-lawyers-in-summerville/"),
        U(P["ride"]+"lyft-accident-lawyers-in-summerville/"), U(P["slip"]), U(P["dog"]), U(P["wd"]), LOC,
        U(C["dorchester"]), U(C["charleston"]), U(C["berkeley"]), U(C["colleton"]), U(C["orangeburg"]), U(C["beaufort"]),
        U(C["georgetown"]), U(C["williamsburg"]), ABOUT, CONTACT],
 outbound=["factbooks", "t15c003"],
 local=["L1","L4","L6","L8","L15","L17"], images="none (homepage images are owned by the site design, flag for Daylin)",
 notes="Reproduce every supplied heading exactly (APA title case already applied). Keep 'Ride Share' as Nick wrote it. The 4.8 star Google rating belongs in the Why Turn section. One warm line about the office dogs Mistoc and Palmer is permitted in the Why Turn section only, and is optional.",
))

PAGES.append(pg(id="pa", phase="A", type="Menu page, practice areas hub", h1="Personal Injury Cases Frost Law Group Handles in Summerville, South Carolina",
 url=PA, slug="/practice-areas", parent="none, root page (menu page, never has children)", wp_title="Practice Areas",
 kp="Summerville personal injury cases", words=(1500, 1950), target=1700,
 replaces="Rewrite in place of the current /practice-areas page", redirect_from=[],
 title="Summerville Personal Injury Cases | See What We Handle",
 desc="Summerville personal injury cases Frost Law Group handles include car, truck, rideshare, motorcycle, dog bite, fall and wrongful death claims. Call to talk.",
 device="Sorted by what hurt you. Vehicles first, then property and animals, then the loss of a life, with each case type defined by who is usually responsible and whose insurance usually answers for it.",
 h2=["Motor Vehicle Crash Cases Our Summerville Personal Injury Lawyers Handle",
     "Premises and Dog Bite Injury Cases for Summerville Accident Attorneys",
     "Wrongful Death Claims a Summerville Injury Attorney Pursues for Families",
     "Ask a Summerville Injury Lawyer Which Claim Fits Your Accident"],
 h2_notes="Under H2 1 put H3s for car, truck, motorcycle and rideshare (each links its parent). Under the truck H3 put two H4s (tractor trailers, delivery trucks) linking those children. Under the rideshare H3 put two H4s (Uber, Lyft) linking those children. Under H2 2 put H3s for slip and fall and dog bites (link parents). Under H2 3 put two H3s, one for fatal crash claims under the Wrongful Death Act (link wrongful death parent) and one for survival claims (link survival action child). Keep every section short, this is a menu page of about 1,700 words. H5 is not required on this page.",
 first_link=(HOME, "'Frost Law Group' pointing to the homepage"),
 links=[HOME, U(P["car"]), U(P["truck"]), U(P["truck"]+"tractor-trailer-accident-lawyers-in-summerville/"),
        U(P["truck"]+"delivery-truck-accident-lawyers-in-summerville/"), U(P["moto"]), U(P["ride"]),
        U(P["ride"]+"uber-accident-lawyers-in-summerville/"), U(P["ride"]+"lyft-accident-lawyers-in-summerville/"),
        U(P["slip"]), U(P["dog"]), U(P["wd"]), U(P["wd"]+"survival-action-lawyers-in-summerville/"), LOC, CONTACT],
 outbound=["t15c003"], local=["L15","L1"], images="parent",
 notes="Menu page. The H1 is Nick's approved string and does not equal the slug. The exact keyphrase 'Summerville personal injury cases' goes in the first 100 words, one body H2 is NOT required to carry it exactly (the H2s are fixed above), and the CTA section text must carry it. Do not name workers compensation.",
))

PAGES.append(pg(id="loc", phase="A", type="Menu page, locations hub", h1="South Carolina Personal Injury Attorneys Serving Summerville and the Surrounding Counties",
 url=LOC, slug="/locations/", parent="none, root page (menu page, never has children)", wp_title="Locations",
 kp="South Carolina personal injury attorneys", words=(5040, 6000), target=5300, replaces="New page", redirect_from=[],
 title="South Carolina Personal Injury Attorneys | Call Frost First",
 desc="South Carolina personal injury attorneys at Frost Law Group serve eight counties from our Summerville office. Find your county and call for a free consultation.",
 device="Judicial circuit order. The eight counties run in circuit order, First Circuit (Dorchester, Orangeburg), Ninth (Charleston, Berkeley), Fourteenth (Colleton, Beaufort), Fifteenth (Georgetown), Third (Williamsburg), so the page explains where a claim from each county is filed and how the circuits connect back to a Summerville office.",
 h2=["How South Carolina Personal Injury Attorneys Decide Where a Claim Is Filed",
     "Dorchester County Injury Claims Our Summerville Lawyers Handle Close to Home",
     "Orangeburg County Crash Cases in the Same Circuit as Our Summerville Attorneys",
     "Charleston County Serious Injury Claims and the Lawyers Who Take Them On",
     "Berkeley County Accident Cases for a Fast Growing Community's Injury Attorneys",
     "Colleton County I-95 Crash Claims Handled by Lowcountry Injury Lawyers",
     "Beaufort County Injury Cases Without an Interstate for Our Accident Attorneys",
     "Georgetown County US 17 Crash Claims Our Personal Injury Lawyers Review",
     "Williamsburg County Rural Road Injuries and the Attorneys Who Handle Them",
     "Talk With South Carolina Personal Injury Attorneys Who Answer From Summerville"],
 h2_notes="Approved 2026-09-14: every county gets its own H2, links once to its county parent, and runs at least two developed paragraphs of county-specific detail. That makes 10 H2s, which the approval allows. Put the page's H4, H5 depth in H2 1 (Circuit Court, Court of Common Pleas, venue in the county where a defendant lives or the crash happened only if verified, the eight circuits map) and give each county H2 one or two H3s whose wording is unique to that county. Never use the formula 'Where a X County Case Is Filed' more than once. Never write the county page H1 string 'Personal Injury Attorneys in X County'.",
 first_link=(HOME, "'Frost Law Group' pointing to the homepage"),
 links=[HOME, U(C["dorchester"]), U(C["orangeburg"]), U(C["charleston"]), U(C["berkeley"]), U(C["colleton"]),
        U(C["beaufort"]), U(C["georgetown"]), U(C["williamsburg"]), PA, CONTACT],
 outbound=["courts_circuit", "dph_trauma"], local=["pack section 5 for every county"], images="parent",
 notes="Summerville-first, Lowcountry-second. Never claim statewide service. Say the firm serves eight counties. Beaufort section, no Georgia anything.",
))

def parent(id, key, h1, target, title, desc, device, h2, links, outbound, local, replaces, notes=""):
    PAGES.append(pg(id=id, phase="A", type="Practice area parent page", h1=h1, url=U(P[key]), slug=P[key],
      parent="none, root page", wp_title=h1, kp=h1, words=(5040, 6000), target=target,
      replaces=replaces[0], redirect_from=replaces[1], title=title, desc=desc, device=device, h2=h2,
      first_link=(HOME, "'Frost Law Group' pointing to the homepage"), links=links, outbound=outbound,
      local=local, images="parent", notes=notes))

parent("car", "car", "Car Accident Attorneys in Summerville", 5350,
 "Car Accident Attorneys in Summerville | Get Answers Now",
 "Car Accident Attorneys in Summerville at Frost Law Group explain South Carolina fault rules, insurance, and deadlines after a wreck. Call for a free consultation.",
 "The contributing factor list as a table of contents. The five factors officers recorded most often on Dorchester County reports in 2024 (failed to yield 986, too fast for conditions 823, improper lane usage 415, followed too closely 408, ran off road 339) organize the first half of the page, each tied to the South Carolina rule of the road it breaks and the proof that shows it.",
 ["How Car Accident Attorneys in Summerville Prove a Driver Failed to Yield",
  "What a Summerville Car Crash Lawyer Looks for When Speed Caused the Wreck",
  "Rear End and Lane Change Collisions a Summerville Auto Accident Lawyer Handles",
  "How South Carolina Fault Rules Shape a Summerville Car Wreck Attorney's Case",
  "Insurance Coverage a Car Accident Lawyer in Summerville Can Pursue",
  "Damages a Summerville Auto Crash Attorney Can Seek Under South Carolina Law",
  "Reports and Deadlines Car Accident Attorneys in Summerville Track",
  "Talk to a Summerville Car Accident Lawyer Before You Give a Recorded Statement"],
 [HOME, U(P["car"]+"drunk-driving-accident-lawyers-in-summerville/"), U(P["cat"]),
  U(P["car"]+"hit-and-run-accident-lawyers-in-summerville/"), U(P["ride"]), U(P["truck"]), U(C["dorchester"]), CONTACT],
 ["t56c005", "doi_auto"], ["L9","L11","L12","L10","L1","L19"], ("Replaces /practice-areas/car-accidents", ["/practice-areas/car-accidents"]),
 "Hit and run belongs under the insurance H2 (UM) and links the hit and run child. Drunk driving belongs under the speed or fault discussion and links the DUI child. Catastrophic injury links from the damages H2. The CTA H2 carries 'Car Accident Lawyer' not the exact keyphrase, so put the exact keyphrase in the CTA text.")

parent("truck", "truck", "Truck Accident Attorneys in Summerville", 5550,
 "Truck Accident Attorneys in Summerville | Call Us Today",
 "Truck Accident Attorneys in Summerville at Frost Law Group review federal trucking rules, carrier records, and insurance after a crash. Call for a free consultation.",
 "The weight-class ladder. The page climbs by gross vehicle weight rating, under 10,001 pounds, 10,001 and up in interstate commerce, 26,001 and up (CDL, and South Carolina's intrastate adoption of the federal rules in Section 56-5-4240), then the truck tractor, because each rung changes which rulebook, which records and which insurance minimum apply.",
 ["Why Truck Accident Attorneys in Summerville Start With the Vehicle's Weight Rating",
  "Federal Hours of Service Rules a Summerville Semi Truck Lawyer Checks First",
  "What a Summerville 18 Wheeler Accident Lawyer Examines After an I-26 Crash",
  "Delivery Vans and Box Trucks Handled by a Commercial Vehicle Lawyer in Summerville",
  "Which Companies a Summerville Truck Crash Attorney Can Hold Responsible",
  "Records a Truck Accident Lawyer in Summerville Must Request Before They Disappear",
  "How Summerville Truck Wreck Attorneys Handle Shared Fault Under the 2026 Law",
  "Call Frost First and Speak With Truck Accident Attorneys in Summerville"],
 [HOME, U(P["truck"]+"tractor-trailer-accident-lawyers-in-summerville/"), U(P["truck"]+"delivery-truck-accident-lawyers-in-summerville/"),
  U(P["truck"]+"truck-driver-fatigue-accident-lawyers-in-summerville/"), U(P["wd"]+"fatal-truck-accident-lawyers-in-summerville/"),
  U(P["car"]), U(C["charleston"]+"truck-accident-lawyers-in-charleston-county/"), CONTACT],
 ["ecfr_390_5", "ecfr_387_9"], ["L13","L8","L5","L21 statewide CMV figures"], ("Replaces /practice-areas/truck-accidents", ["/practice-areas/truck-accidents"]),
 "The September 14 name was Commercial Truck Accident Attorneys in Summerville. The approved manifest H1 drops Commercial. Give commercial vehicles a heavy section inside. Never write that trucks cause most fatal truck crashes (Fact Book trap). I-26 exits near Summerville are labeled Berkeley County by SCDOT.")

parent("moto", "moto", "Motorcycle Accident Attorneys in Summerville", 5200,
 "Motorcycle Accident Attorneys in Summerville | Call Today",
 "Motorcycle Accident Attorneys in Summerville at Frost Law Group handle left turn, lane, and uninsured driver crashes across the Lowcountry. Call to talk today.",
 "Sight lines. Each major section is a place where a driver's view of a rider breaks down (an oncoming left turn, a lane change, the rear approach, a side road pull-out, dusk and evening riding), and each ends with the proof that answers 'I never saw the motorcycle.'",
 ["How Motorcycle Accident Attorneys in Summerville Prove a Driver Should Have Seen You",
  "What a Summerville Motorcycle Crash Lawyer Shows When a Car Turned Left",
  "Lane Rights and the Lane Splitting Ban a Summerville Biker Injury Lawyer Explains",
  "Does Skipping a Helmet Hurt a Claim With a Summerville Motorcycle Injury Attorney",
  "Uninsured Drivers and Hit and Run Crashes a Summerville Motorcycle Lawyer Sees",
  "Weekend and Evening Ride Risks Summerville Motorcycle Accident Lawyers Track",
  "Injuries, Bike Damage, and Gear a Summerville Motorcycle Wreck Attorney Values",
  "Speak With Motorcycle Accident Attorneys in Summerville Who Answer the Phone"],
 [HOME, U(P["moto"]+"left-turn-motorcycle-accident-lawyers-in-summerville/"), U(P["moto"]+"motorcycle-helmet-law-injury-lawyers-in-summerville/"),
  U(P["moto"]+"uninsured-motorist-motorcycle-lawyers-in-summerville/"), U(P["car"]+"hit-and-run-accident-lawyers-in-summerville/"),
  U(C["charleston"]+"motorcycle-accident-lawyers-in-charleston-county/"), U(C["berkeley"]+"motorcycle-accident-lawyers-in-berkeley-county/"), CONTACT],
 ["t56c005", "factbooks"], ["L15 motorcyclist victims","L9","L6","L21 statewide motorcycle"], ("Replaces /practice-areas/motorcycle-accidents", ["/practice-areas/motorcycle-accidents"]),
 "Civil effect of not wearing a helmet is NOT verified. Say the insurer may raise it, that fault and causation turn on the facts, and never state a rule. Use 132 motorcyclists killed, never 134.")

parent("ride", "ride", "Rideshare Accident Attorneys in Summerville", 5100,
 "Rideshare Accident Attorneys in Summerville | Ask Us First",
 "Rideshare Accident Attorneys in Summerville at Frost Law Group sort out app status, driver coverage, and fault after an Uber or Lyft crash. Call for a free review.",
 "App status timeline. The page follows a rideshare driver's app through its states (app off, logged in and waiting, ride accepted and en route, passenger aboard, drop-off), because South Carolina's TNC Act changes the required coverage at each step.",
 ["Why Rideshare Accident Attorneys in Summerville Ask Where the Driver's App Stood",
  "Who Can Bring a Claim With a Summerville Rideshare Crash Lawyer",
  "Driver Screening Rules a Rideshare Injury Attorney in Summerville Can Check",
  "How a Summerville Rideshare Attorney Gets the Insurance Facts After a Crash",
  "How a Summerville Rideshare Collision Lawyer Divides Fault Among Drivers",
  "Deadlines and Records a Summerville Uber and Lyft Accident Attorney Watches",
  "Ask Rideshare Accident Attorneys in Summerville What Your Driver's App Status Means"],
 [HOME, U(P["ride"]+"uber-accident-lawyers-in-summerville/"), U(P["ride"]+"lyft-accident-lawyers-in-summerville/"),
  U(P["car"]), U(P["cat"]), LOC, CONTACT],
 ["t58c023", "dmv_reports"], ["L4","L5","L17","L6"], ("New page", []),
 "Uber's and Lyft's actual policy limits are NOT verified. Only state the statute's minimums. The statute does not call TNCs common carriers. Never claim a $1 million UM or UIM requirement. Under H2 2 give passengers (link Uber child from an Uber passenger H3, Lyft child from a Lyft passenger H3), other drivers, pedestrians and the rideshare driver their own H3s.")

parent("slip", "slip", "Slip and Fall Attorneys in Summerville", 5150,
 "Slip and Fall Attorneys in Summerville | Speak With Us",
 "Slip and Fall Attorneys in Summerville at Frost Law Group explain what South Carolina law requires you to prove after a fall on someone's property. Call today.",
 "What was on the floor and how long it was there. The Wintersteen framework is the spine, the owner created the hazard, the owner knew, or the owner should have known because it was there long enough, followed by who you were on the property and what the owner will argue.",
 ["What Slip and Fall Attorneys in Summerville Must Prove Under the Wintersteen Rule",
  "How a Summerville Premises Injury Lawyer Shows the Owner Created the Hazard",
  "When a Summerville Fall Injury Attorney Proves the Owner Knew About the Danger",
  "Why Your Reason for Being There Matters to a Slip and Fall Lawyer in Summerville",
  "How a Summerville Trip and Fall Lawyer Answers the Open and Obvious Defense",
  "Store, Apartment, and Government Property Falls a Summerville Injury Attorney Handles",
  "Slip and Fall Attorneys in Summerville Can Review Your Photos and Incident Report"],
 [HOME, U(P["slip"]+"retail-slip-and-fall-lawyers-in-summerville/"), U(P["slip"]+"apartment-injury-lawyers-in-summerville/"),
  U(P["slip"]+"premises-liability-lawyers-in-summerville/"), U(P["dog"]), PA, CONTACT],
 ["wintersteen", "t15c078"], ["L6","L7","L1","L2"], ("Replaces /practice-areas/slip-and-fall", ["/practice-areas/slip-and-fall"]),
 "Wintersteen rejected liability based on the store's method of display and any duty to prevent. Do not call it 'mode of operation' as a quote. Fact Book crash data excludes parking lots, irrelevant here, never mix.")

parent("dog", "dog", "Dog Bite Attorneys in Summerville", 5050,
 "Dog Bite Attorneys in Summerville | Call Frost First",
 "Dog Bite Attorneys in Summerville at Frost Law Group explain South Carolina's strict liability statute and who pays after an attack. Call for a free consultation.",
 "Where the bite happened. Section 47-3-110 turns on location and lawful presence, so the page walks the places a bite happens (public places, the owner's home, someone else's property, rental property) and then the defenses, reports and insurance that follow.",
 ["How Dog Bite Attorneys in Summerville Use South Carolina's Strict Liability Statute",
  "What a Summerville Dog Attack Lawyer Proves After a Bite in a Public Place",
  "Bites on Private Property and What a Summerville Dog Bite Lawyer Must Show",
  "Provocation and Other Defenses a Summerville Animal Attack Attorney Expects",
  "How a Summerville Dog Bite Injury Attorney Handles a Child's Claim",
  "Bite Reports and Rabies Quarantine Rules a Summerville Dog Bite Lawyer Tracks",
  "Whose Insurance Pays When a Summerville Dog Bite Lawyer Files a Claim",
  "Call Dog Bite Attorneys in Summerville Before the Insurer Calls You"],
 [HOME, U(P["dog"]+"dog-bite-strict-liability-lawyers-in-summerville/"), U(P["dog"]+"child-dog-bite-injury-lawyers-in-summerville/"),
  U(P["dog"]+"dog-bite-insurance-claim-lawyers-in-summerville/"), U(P["slip"]+"apartment-injury-lawyers-in-summerville/"), LOC, CONTACT],
 ["t47c003", "dph_rabies"], ["L6","L8 MUSC pediatric","L17"], ("Replaces /practice-areas/dog-bites", ["/practice-areas/dog-bites"]),
 "Local dog or leash ordinances are NOT verified, never cite one. DHEC was abolished July 1, 2024. Bite reports now go to SC DPH, say so. Minors, one year after turning 18 is the cap in 15-3-40.")

parent("wd", "wd", "Wrongful Death Attorneys in Summerville", 5250,
 "Wrongful Death Attorneys in Summerville | Talk With Us",
 "Wrongful Death Attorneys in Summerville at Frost Law Group guide families through South Carolina's wrongful death and survival claims. Call to talk with us.",
 "The statute's family tree. Section 15-51-20 decides who benefits (spouse and children, then parents, then heirs) and who signs (the personal representative), so the page moves from the family, to the probate appointment, to the two claims, to damages, settlement approval and the deadline.",
 ["Who Wrongful Death Attorneys in Summerville Represent Under Section 15-51-20",
  "How a Summerville Wrongful Death Lawyer Opens the Estate in Probate Court",
  "Wrongful Death and Survival Claims a Summerville Fatal Accident Attorney Brings Together",
  "Fatal Car and Truck Crashes a Summerville Wrongful Death Lawyer Investigates",
  "Damages a Family Can Seek Through a Summerville Wrongful Death Attorney",
  "How Courts Approve a Settlement Reached by a Summerville Wrongful Death Lawyer",
  "The Three-Year Filing Deadline a Summerville Wrongful Death Attorney Tracks",
  "Wrongful Death Attorneys in Summerville Who Will Sit Down With Your Family"],
 [HOME, U(P["wd"]+"fatal-car-accident-lawyers-in-summerville/"), U(P["wd"]+"survival-action-lawyers-in-summerville/"),
  U(P["wd"]+"fatal-truck-accident-lawyers-in-summerville/"), U(P["car"]), U(P["truck"]), ABOUT, CONTACT],
 ["t15c051", "t15c005"], ["L20","L1","L15 killed 37","L8"], ("Replaces /practice-areas/wrongful-death", ["/practice-areas/wrongful-death"]),
 "Tara's former Associate Probate Judge service is perspective only, never tied to the sitting Dorchester County Probate Court as influence. Do not name the sitting probate judge. Whether creditors can reach wrongful death proceeds is NOT verified, do not state it.")

# ---------------------------------------------------------------- PHASE B, county parents
def county(id, key, target, title, desc, device, h2, links, outbound, notes=""):
    h1 = f"Personal Injury Attorneys in {key.capitalize()} County"
    PAGES.append(pg(id=id, phase="B", type="County parent page", h1=h1, url=U(C[key]), slug=C[key],
      parent="none, root page", wp_title=h1, kp=h1, words=(5040, 6000), target=target, replaces="New page", redirect_from=[],
      title=title, desc=desc, device=device, h2=h2, first_link=(HOME, "'Frost Law Group' pointing to the homepage"),
      links=links, outbound=outbound, local=[f"county pack: {key.capitalize()} entry and section 5"], images="parent", notes=notes))

county("co-dorchester", "dorchester", 5150,
 "Personal Injury Attorneys in Dorchester County | Talk to Us",
 "Personal Injury Attorneys in Dorchester County at Frost Law Group handle crash and injury claims from St. George to Ridgeville. Call for a free consultation.",
 "From the courthouse outward. The page starts at the Dorchester County Courthouse in St. George, where Common Pleas claims are filed, then moves out through the upper county towns, the unincorporated communities and the corridors that carry the county's crashes. Summerville appears only as the office location.",
 ["Why Personal Injury Attorneys in Dorchester County File Claims in St. George",
  "Injury Claims From Ridgeville, Harleyville, and Reevesville With a Dorchester County Lawyer",
  "Knightsville, Ladson, and Other Unincorporated Communities a Dorchester County Attorney Serves",
  "Dorchester Road and I-95 Crash Claims a Dorchester County Accident Lawyer Reviews",
  "Failure to Yield and Speed, the Crash Causes Dorchester County Injury Lawyers See Most",
  "Hospital and Trauma Records a Dorchester County Personal Injury Lawyer Gathers",
  "Magistrate Court Limits a Dorchester County Injury Lawyer Explains to Clients",
  "Call Personal Injury Attorneys in Dorchester County Who Live and Work Here"],
 [HOME, U(P["car"]), U(P["truck"]), U(P["moto"]), U(C["orangeburg"]), U(C["berkeley"]), LOC, CONTACT],
 ["courts_dorchester", "t22c003"],
 "Decided 2026-09-15: rest-of-county hub. Center the body on St. George, Ridgeville, Harleyville, Reevesville and Knightsville with county-wide 2024 data. Summerville appears only as the office location, with links up to the homepage and the Summerville car, truck and motorcycle parents. Never repeat Summerville practice content. Knightsville and Ladson are unincorporated, never towns. The Troy Knight Judicial Complex houses Family Court, the Summerville Magistrate Court and Central Bond Court (research correction). Tara's service as a Dorchester County Magistrate Judge is past tense, perspective only.")

county("co-charleston", "charleston", 5450,
 "Personal Injury Attorneys in Charleston County | Call Today",
 "Personal Injury Attorneys in Charleston County at Frost Law Group handle serious crash and injury claims from North Charleston to the islands. Call for a free review.",
 "Serious injury as the organizing fact. Charleston County led all 46 counties in serious injury collisions in 2024, so every section asks what that severity means for the claim, the medical record, the corridor and the courthouse.",
 ["Why Personal Injury Attorneys in Charleston County See So Many Serious Injury Crashes",
  "US 17, I-26, and US 52 Corridors a Charleston County Injury Lawyer Tracks",
  "The I-26 Interchanges Behind Charleston County's Worst Intersections for Crash Attorneys",
  "Distracted Driving Claims a Charleston County Car Wreck Lawyer Builds",
  "Two Trauma Centers and the Records a Charleston County Injury Attorney Gathers",
  "Filing at 100 Broad Street With a Charleston County Personal Injury Lawyer",
  "Car, Truck, and Motorcycle Claims Our Lawyers Handle Across Charleston County",
  "Talk With Personal Injury Attorneys in Charleston County Before You Sign Anything"],
 [HOME, U(C["charleston"]+"car-accident-lawyers-in-charleston-county/"), U(C["charleston"]+"truck-accident-lawyers-in-charleston-county/"),
  U(C["charleston"]+"motorcycle-accident-lawyers-in-charleston-county/"), U(C["berkeley"]), U(C["dorchester"]), LOC, CONTACT],
 ["dph_trauma", "courts_search"],
 "Secondary route numbers are county-specific (S-13 is Remount Road in Charleston). For the I-26 intersections write the route numbers as recorded in the Fact Book, do not guess street names for S-75, S-1342 or S-195. The county listed-factor count for distraction (2,965) cannot be compared with the statewide primary-factor count. Charleston County's municipality count is not verified, do not print a number.")

county("co-berkeley", "berkeley", 5300,
 "Personal Injury Attorneys in Berkeley County | Talk With Us",
 "Personal Injury Attorneys in Berkeley County at Frost Law Group handle crash claims from Goose Creek to Moncks Corner as the county grows. Call for a free review.",
 "Growth. The county added roughly 45,000 residents between 2020 and 2025, and each section reads the crash, medical and court picture through that growth, beginning with the county's unusual top factor, driving too fast for conditions.",
 ["How Growth Shapes the Work of Personal Injury Attorneys in Berkeley County",
  "Speed for Conditions, the Leading Crash Factor a Berkeley County Accident Lawyer Sees",
  "College Park Road and Jedburg Road Interchange Crashes in a Berkeley County Attorney's Files",
  "Goose Creek, Hanahan, and Moncks Corner Claims a Berkeley County Injury Lawyer Handles",
  "Hospital Records a Berkeley County Injury Attorney Collects When No Trauma Center Is Local",
  "The Ninth Circuit and the Moncks Corner Courthouse for Berkeley County Injury Lawyers",
  "Car, Truck, and Motorcycle Crash Claims Our Berkeley County Lawyers Take On",
  "Personal Injury Attorneys in Berkeley County Ready to Hear What Happened"],
 [HOME, U(C["berkeley"]+"car-accident-lawyers-in-berkeley-county/"), U(C["berkeley"]+"truck-accident-lawyers-in-berkeley-county/"),
  U(C["berkeley"]+"motorcycle-accident-lawyers-in-berkeley-county/"), U(C["charleston"]), U(C["dorchester"]), LOC, CONTACT],
 ["scdot_trafficdata", "courts_search"],
 "Do not write that US 17 is the deadliest road in Berkeley (SCDOT shows only US 17A in Berkeley). Roper St. Francis Berkeley Hospital has a Summerville address and sits in Berkeley County. Summerville is partly in Berkeley County (5,798 residents, Census 2025 estimate). S-16 is Jedburg Road and S-62 is College Park Road in Berkeley only.")

county("co-colleton", "colleton", 5100,
 "Personal Injury Attorneys in Colleton County | Call Us Today",
 "Personal Injury Attorneys in Colleton County at Frost Law Group handle I-95 and rural road crash claims around Walterboro. Call for a free, confidential review.",
 "The I-95 corridor, interchange by interchange. The five worst intersections in the county all sit on I-95, so the page is organized along that corridor and then off it, into the rural roads where run-off-road crashes dominate.",
 ["Why Personal Injury Attorneys in Colleton County Focus on I-95",
  "Run Off Road and Animal Crashes a Colleton County Accident Lawyer Investigates",
  "What Colleton County's High Death Rate Means for an Injury Attorney",
  "Walterboro, Edisto Beach, and Cottageville Claims a Colleton County Injury Lawyer Handles",
  "Colleton Hospital Records and the Trauma Question for a Colleton County Lawyer",
  "Filing in Walterboro and the Fourteenth Circuit With a Colleton County Attorney",
  "Reach Personal Injury Attorneys in Colleton County Through Our Summerville Office"],
 [HOME, U(C["beaufort"]), U(C["dorchester"]), U(P["truck"]), U(P["car"]), LOC, CONTACT],
 ["dph_trauma", "courts_search"],
 "Green Pond and Hendersonville are SCDOT road names only, never populated places. No trauma center in county. Do not print distances. CORRECTION: Colleton's 43.1 deaths per 100,000 is the SECOND highest of the eight counties, behind Orangeburg's 57.7. Never call it the highest. It is still more than three times Berkeley's 13.9.")

county("co-orangeburg", "orangeburg", 5200,
 "Personal Injury Attorneys in Orangeburg County | Reach Us",
 "Personal Injury Attorneys in Orangeburg County at Frost Law Group handle I-26 and I-95 crash claims in the same circuit as Summerville. Call for a free review.",
 "Size against lethality. Orangeburg ranked 8th of 46 counties for fatal collisions on a population of 83,177, so the page sets each fact about the county's roads, towns, courts and care against that gap between size and severity.",
 ["What Personal Injury Attorneys in Orangeburg County See in the Fatal Crash Data",
  "Why the First Judicial Circuit Links Orangeburg County Claims to Our Summerville Lawyers",
  "I-26 and I-95 Crash Claims an Orangeburg County Accident Attorney Handles",
  "Santee, Holly Hill, and Other Orangeburg County Towns Our Injury Lawyers Serve",
  "Hospital Care at MUSC Health Orangeburg and the Records an Injury Attorney Needs",
  "Five Years of Orangeburg County Crash Data an Accident Lawyer Reviews",
  "Personal Injury Attorneys in Orangeburg County You Can Reach From the Same Circuit"],
 [HOME, U(C["dorchester"]), U(C["colleton"]), U(P["wd"]), U(P["truck"]), LOC, CONTACT],
 ["courts_search", "factbooks"],
 "The Orangeburg trauma level has a source discrepancy. Do NOT state a trauma level. Write 'MUSC Health Orangeburg, formerly The Regional Medical Center'. The courthouse is at 1406 Amelia Street. Orangeburg is in Highway Patrol Troop Seven. VERIFIED: Orangeburg had the HIGHEST death rate of the eight counties on both measures in 2024, 57.7 per 100,000 residents and 2.797 per 100 million vehicle miles.")

county("co-beaufort", "beaufort", 5250,
 "Personal Injury Attorneys in Beaufort County | Get Answers",
 "Personal Injury Attorneys in Beaufort County at Frost Law Group handle crash and injury claims from Bluffton to the Sea Islands. Call for a free consultation.",
 "Corridor by corridor, with no interstate. Beaufort County has no interstate at all, so the page is organized by its named US and SC routes and island parkways, then by what the absence of an in-county trauma center means for serious injury claims.",
 ["How Personal Injury Attorneys in Beaufort County Handle Crashes Without an Interstate",
  "US 278 and William Hilton Parkway Claims a Hilton Head Island Injury Lawyer Reviews",
  "Robert Smalls Parkway and Ribaut Road Crash Claims a Beaufort County Accident Lawyer Handles",
  "Island Communities a Beaufort County Injury Attorney Serves From Daufuskie to Fripp",
  "No Trauma Center in County and the Records a Beaufort County Injury Lawyer Documents",
  "The Beaufort County Courthouse and the Fourteenth Circuit for Personal Injury Lawyers",
  "What the Low Death Rate Hides, Explained by a Beaufort County Crash Attorney",
  "Call Personal Injury Attorneys in Beaufort County Before the Insurer Sets the Pace"],
 [HOME, U(C["colleton"]), U(P["car"]), U(P["moto"]), LOC, CONTACT],
 ["dph_trauma", "courts_search"],
 "HARD RULE, no Georgia city, county, court, road, landmark, hospital or the word Georgia. Never write Savannah or Savannah Highway. Nearest South Carolina trauma center is MUSC in Charleston, write only that a patient may be transported there. Naval Hospital Beaufort is not a civilian crash facility. Ridgeland is excluded. No Beaufort road collision counts exist in the pack, name corridors without counts. CORRECTION: Beaufort's 13.3 deaths per 100,000 residents is the LOWEST of the eight counties. Its 1.611 per 100 million miles is NOT the lowest (Charleston's 1.303 is).")

county("co-georgetown", "georgetown", 5100,
 "Personal Injury Attorneys in Georgetown County | Talk to Us",
 "Personal Injury Attorneys in Georgetown County at Frost Law Group handle US 17 and rural crash claims from Murrells Inlet to Andrews. Call for a free review.",
 "One road county. US 17 carried 42% of the county's 2024 collisions, so the page runs along US 17 first and then outward to the rural US and SC routes, the towns, the care and the courthouse.",
 ["Why Personal Injury Attorneys in Georgetown County Center Their Work on US 17",
  "US 701 and US 521 Rural Crash Claims a Georgetown County Accident Lawyer Handles",
  "Murrells Inlet, Pawleys Island, and Andrews Claims a Georgetown County Injury Attorney Takes",
  "The Only Level IV Trauma Center in Our Service Area and a Georgetown County Lawyer's Records",
  "Filing at the Georgetown County Courthouse in the Fifteenth Circuit With an Injury Lawyer",
  "Speak With Personal Injury Attorneys in Georgetown County About Your Crash"],
 [HOME, U(C["williamsburg"]), U(C["berkeley"]), U(P["car"]), LOC, CONTACT],
 ["dph_trauma", "courts_search"],
 "No interstate. Murrells Inlet straddles Georgetown and Horry, Tidelands Waccamaw at 4070 Highway 17 South is in Georgetown County. Andrews straddles Georgetown and Williamsburg, write it differently from the Williamsburg page. Nearest Level I is Grand Strand Medical Center in Myrtle Beach (Horry County).")

county("co-williamsburg", "williamsburg", 5050,
 "Personal Injury Attorneys in Williamsburg County | Call Us",
 "Personal Injury Attorneys in Williamsburg County at Frost Law Group handle rural road crash claims around Kingstree, Hemingway, and Lane. Call for a free review.",
 "Rural hazards. The county's top listed crash factors are ran off road, too fast for conditions and animal in the road, so the page follows those rural hazards across the county's secondary and SC routes, then the care and court facts that are unique here.",
 ["What Personal Injury Attorneys in Williamsburg County See on Rural Roads",
  "SC 261 and US 52 Crash Claims a Williamsburg County Accident Lawyer Reviews",
  "Animal in the Road Crashes and the Claims a Williamsburg County Injury Attorney Pursues",
  "Hospital Care in Cades and the Records a Williamsburg County Injury Lawyer Collects",
  "The Kingstree Courthouse and the Third Circuit for Williamsburg County Accident Lawyers",
  "Rising Fatalities in a Shrinking County, Tracked by a Williamsburg County Crash Attorney",
  "Talk With Personal Injury Attorneys in Williamsburg County From Our Summerville Office"],
 [HOME, U(C["georgetown"]), U(P["car"]), U(P["wd"]), LOC, CONTACT],
 ["dph_trauma", "courts_search"],
 "Williamsburg Regional Hospital in Kingstree closed in January 2023. The operating hospital is MUSC Health Black River Medical Center in Cades. Never put a hospital in Kingstree. No CDPs in the county. No interstate. No distances. Livestock or animal owner liability law is NOT verified, do not state a legal rule about it.")

# ---------------------------------------------------------------- PHASE C, practice children
def child(id, pkey, slug, h1, target, title, desc, device, h2, links, outbound, local, notes="", replaces=("New page", []), phase="C"):
    url = U(P[pkey] + slug + "/")
    PAGES.append(pg(id=id, phase=phase, type="Practice area child page", h1=h1, url=url, slug=P[pkey]+slug+"/",
      parent=U(P[pkey]), wp_title=h1, kp=h1, words=(3040, 3700), target=target, replaces=replaces[0], redirect_from=replaces[1],
      title=title, desc=desc, device=device, h2=h2, first_link=(U(P[pkey]), "'Frost Law Group' pointing to this page's parent"),
      links=links, outbound=outbound, local=local, images="child", notes=notes))

child("car-dui", "car", "drunk-driving-accident-lawyers-in-summerville", "Drunk Driving Accident Lawyers in Summerville", 3250,
 "Drunk Driving Accident Lawyers in Summerville | Talk to Us",
 "Drunk Driving Accident Lawyers in Summerville at Frost Law Group explain the 2026 changes to South Carolina DUI crash claims. Call for a free consultation.",
 "Before and after January 1, 2026. Act No. 42 applies to claims arising after January 1, 2026, so the page sets each part of a drunk driving claim (the driver, the bar, the verdict form, punitive damages) against the old rule and the new one.",
 ["How Drunk Driving Accident Lawyers in Summerville Use the Criminal DUI Case",
  "What Changed on January 1, 2026, for a Summerville DUI Crash Lawyer's Clients",
  "Bars and Restaurants a Summerville Drunk Driver Accident Attorney Can Name",
  "Underage Drinking Parties and Social Host Claims a Summerville DUI Injury Lawyer Reviews",
  "Why a Summerville Impaired Driving Crash Lawyer Looks at Punitive Damages",
  "Speak With Drunk Driving Accident Lawyers in Summerville About Both Cases"],
 [U(P["car"]), U(P["car"]+"hit-and-run-accident-lawyers-in-summerville/"), U(P["cat"]), U(P["wd"]), CONTACT],
 ["t61c002", "t15c032"], ["L15 DUI estimates","L3","L4"],
 "County DUI death figures are NHTSA estimates, label them as estimates. Never add fatal and non-fatal DUI figures together. The .08 figure lives in 56-5-2933. Bars may carry as little as $300,000 after risk-mitigation credits, never say every bar carries $1 million. Use 'January 1, 2026,' with the comma after the year.")

child("car-cat", "car", "catastrophic-injury-lawyers-in-summerville", "Catastrophic Injury Lawyers in Summerville", 3450,
 "Catastrophic Injury Lawyers in Summerville | Ask Our Team",
 "Catastrophic Injury Lawyers in Summerville at Frost Law Group document lifetime care, lost earning capacity, and coverage limits after a serious crash. Call us.",
 "The decades after discharge. The page follows a catastrophic injury forward in time (trauma care, rehabilitation, home and vehicle changes, the working years, later life) and shows what each stage adds to the claim and how it is proved.",
 ["What Catastrophic Injury Lawyers in Summerville Mean by a Life-Changing Injury",
  "Trauma Care Near Summerville and the Records a Catastrophic Injury Attorney Gathers",
  "Rehabilitation and Home Changes a Summerville Serious Injury Lawyer Documents",
  "How a Summerville Catastrophic Injury Attorney Measures Lost Earning Capacity",
  "How a Summerville Severe Injury Lawyer Handles Medicaid and Medicare Repayment",
  "Damages Caps and Coverage Limits a Summerville Catastrophic Crash Attorney Confronts",
  "Talk With Catastrophic Injury Lawyers in Summerville About Future Care"],
 [U(P["car"]), U(P["car"]+"drunk-driving-accident-lawyers-in-summerville/"), U(P["truck"]), U(P["wd"]+"survival-action-lawyers-in-summerville/"), CONTACT],
 ["t43c007", "dph_trauma"], ["L8","L6","L15 serious injury"],
 "Replaces the old /practice-areas/catastrophic-injuries page (301). Never use the word 'expert'. Say life care planner, vocational rehabilitation counselor, economist, treating physician. The noneconomic cap applies only to medical malpractice. Never write 'South Carolina has no caps'. Medicaid recovery is assignment and subrogation, not a lien. Hospital lien statute is NOT verified, do not mention one.",
 replaces=("Replaces /practice-areas/catastrophic-injuries", ["/practice-areas/catastrophic-injuries"]))

child("car-hr", "car", "hit-and-run-accident-lawyers-in-summerville", "Hit and Run Accident Lawyers in Summerville", 3150,
 "Hit and Run Accident Lawyers in Summerville | Call Today",
 "Hit and Run Accident Lawyers in Summerville at Frost Law Group use your uninsured motorist coverage when the driver flees. Call for a free, confidential review.",
 "Three routes to coverage. Section 38-77-170, rewritten in 2024, gives three ways to prove an unknown driver caused the crash (physical contact, an independent witness, or a recording), and the page is organized around those three routes.",
 ["How Hit and Run Accident Lawyers in Summerville Open an Uninsured Motorist Claim",
  "The Three Proof Routes a Summerville Hit and Run Lawyer Uses Under Section 38-77-170",
  "Why a Summerville Hit and Run Attorney Asks When and How You Reported the Crash",
  "Leaving the Scene Penalties and the Civil Claim a Summerville Accident Lawyer Brings",
  "How a Summerville Hit and Run Crash Attorney Tries to Identify the Missing Driver",
  "Hit and Run Accident Lawyers in Summerville Can Help You Open Your UM Claim"],
 [U(P["car"]), U(P["car"]+"drunk-driving-accident-lawyers-in-summerville/"), U(P["moto"]+"uninsured-motorist-motorcycle-lawyers-in-summerville/"), U(P["ride"]), CONTACT],
 ["t38c077", "t56c005"], ["L4","L5","L16","L19"],
 "The Fact Book has NO statewide hit-and-run total. Never write 8 hit-and-run deaths or 4,699 hit-and-run crashes. The police report deadline in 38-77-170 is 'within a reasonable time', no fixed hours.")

child("truck-tt", "truck", "tractor-trailer-accident-lawyers-in-summerville", "Tractor Trailer Accident Lawyers in Summerville", 3350,
 "Tractor Trailer Accident Lawyers in Summerville | Call Us",
 "Tractor Trailer Accident Lawyers in Summerville at Frost Law Group examine the rig, the load, and the logbook after a semi crash. Call for a free consultation.",
 "Anatomy of the rig. The page moves through the truck itself (brakes and tires, the coupling and trailer, the cargo, the cab and the driver's logbook) and names the rule and the record behind each part.",
 ["Why Tractor Trailer Accident Lawyers in Summerville Inspect the Whole Rig",
  "Brakes, Tires, and Maintenance Records a Summerville 18 Wheeler Lawyer Requests",
  "Cargo and Coupling Failures a Summerville Semi Accident Attorney Examines",
  "Driver Logs and Qualification Files a Summerville Big Rig Crash Lawyer Reviews",
  "Underride, Jackknife, and Wide Turn Crashes Seen by Summerville Truck Injury Lawyers",
  "The Federal Insurance Minimum a Summerville Tractor Trailer Crash Attorney Starts From",
  "Call Tractor Trailer Accident Lawyers in Summerville About the Truck That Hit You"],
 [U(P["truck"]), U(P["truck"]+"truck-driver-fatigue-accident-lawyers-in-summerville/"), U(P["truck"]+"delivery-truck-accident-lawyers-in-summerville/"),
  U(C["charleston"]+"truck-accident-lawyers-in-charleston-county/"), CONTACT],
 ["ecfr_387_9", "t56c005"], ["L13","L21 truck tractor 6,159 statewide"],
 "Truck tractor collisions (6,159, 69 fatal, 80 killed) and commercial vehicle collisions (3,260) use different definitions. Never add or compare them. Out-of-state drivers 42.7% statewide, do not name the states. Load securement exemptions exist for forest products, livestock, poultry and paper loads.")

child("truck-deliv", "truck", "delivery-truck-accident-lawyers-in-summerville", "Delivery Truck Accident Lawyers in Summerville", 3100,
 "Delivery Truck Accident Lawyers in Summerville | Talk to Us",
 "Delivery Truck Accident Lawyers in Summerville at Frost Law Group handle van and box truck crash claims in neighborhoods and on main roads. Call for a free review.",
 "A delivery route, stop by stop. The page follows a delivery vehicle from the depot, onto main roads, into neighborhoods, through backing and curbside stops, and back again, asking at each stop which rules apply and who employs the driver.",
 ["Why Delivery Truck Accident Lawyers in Summerville Follow the Driver's Route",
  "Neighborhood Stops and Backing Crashes a Summerville Delivery Van Lawyer Handles",
  "Employee or Contractor, the Question a Summerville Box Truck Accident Attorney Asks",
  "Federal and State Rules a Summerville Commercial Van Accident Lawyer Applies by Weight",
  "Route Data and Scanner Records a Summerville Delivery Crash Attorney Requests",
  "Delivery Truck Accident Lawyers in Summerville Ready to Review Your Crash"],
 [U(P["truck"]), U(P["truck"]+"tractor-trailer-accident-lawyers-in-summerville/"), U(P["car"]), U(P["slip"]+"premises-liability-lawyers-in-summerville/"), CONTACT],
 ["ecfr_390_5", "t56c005"], ["L12","L11","L17"],
 "Never name a delivery company or claim a company's practices, quotas or insurance. Describe route data and handheld scanner records generally, as things a lawyer may request if they exist. Vehicles under 10,001 lb are not CMVs under 49 CFR 390.5. South Carolina applies the FMCSRs to in-state trucks only at 26,001 lb or more (56-5-4240).")

child("truck-fatigue", "truck", "truck-driver-fatigue-accident-lawyers-in-summerville", "Truck Driver Fatigue Accident Lawyers in Summerville", 3200,
 "Truck Driver Fatigue Accident Lawyers in Summerville",
 "Truck Driver Fatigue Accident Lawyers in Summerville at Frost Law Group rebuild a trucker's duty day from logs and ELD data. Call for a free consultation today.",
 "The 14-hour clock. The page rebuilds one driver's duty day hour by hour against the hours of service rules, the 10 hours off, the 14-hour window, the 11 hours of driving, the 30-minute break and the weekly limits, and shows which record proves each one.",
 ["How Truck Driver Fatigue Accident Lawyers in Summerville Rebuild the Duty Day",
  "The 11-Hour Driving Limit and 14-Hour Window a Summerville Tired Trucker Lawyer Tests",
  "Electronic Logging Device Data a Summerville Fatigued Driver Crash Attorney Preserves",
  "Break and Weekly Limit Violations a Summerville Truck Crash Lawyer Looks For",
  "When a Carrier Pushed the Schedule, What a Summerville Trucking Fatigue Lawyer Proves",
  "Signs of Drowsy Driving a Summerville Truck Accident Attorney Reads in the Evidence",
  "Call Truck Driver Fatigue Accident Lawyers in Summerville While the Logs Still Exist"],
 [U(P["truck"]), U(P["truck"]+"tractor-trailer-accident-lawyers-in-summerville/"), U(P["wd"]+"fatal-truck-accident-lawyers-in-summerville/"),
  U(C["berkeley"]+"truck-accident-lawyers-in-berkeley-county/"), CONTACT],
 ["ecfr_395_3", "ecfr_395_8"], ["L13","L5"],
 "The SEO title is the keyphrase alone because the keyphrase and a sensible CTA do not fit in 60 characters (house rule). Keyphrase is 52 characters, hold the exact phrase to the H1, the first 100 words, H2 1, the CTA H2 and the CTA text.")

child("moto-left", "moto", "left-turn-motorcycle-accident-lawyers-in-summerville", "Left Turn Motorcycle Accident Lawyers in Summerville", 3100,
 "Left Turn Motorcycle Accident Lawyers in Summerville",
 "Left Turn Motorcycle Accident Lawyers in Summerville at Frost Law Group prove when a driver turned into a rider's path. Call for a free, confidential consultation.",
 "Four kinds of left turn. Section 56-5-2320 covers turns at an intersection and into an alley, a private road or a driveway, so the page takes each kind of turn in turn, then the speeding defense and the injuries these impacts cause.",
 ["How Left Turn Motorcycle Accident Lawyers in Summerville Apply Section 56-5-2320",
  "Intersection Turns a Summerville Motorcycle Crash Attorney Sees on Dorchester Road",
  "Driveway and Side Street Turns a Summerville Biker Accident Lawyer Investigates",
  "How a Summerville Motorcycle Accident Attorney Answers the Speeding Defense",
  "Injuries From Left Turn Impacts a Summerville Rider Injury Lawyer Documents",
  "Left Turn Motorcycle Accident Lawyers in Summerville Ready to Review the Scene"],
 [U(P["moto"]), U(P["moto"]+"motorcycle-helmet-law-injury-lawyers-in-summerville/"), U(P["moto"]+"uninsured-motorist-motorcycle-lawyers-in-summerville/"), U(P["car"]), CONTACT],
 ["t56c005", "factbooks"], ["L9","L12","L15 motorcyclist victims"],
 "The Dorchester Road intersection counts are all-crash counts, never say they were motorcycle crashes. Keyphrase alone as SEO title (house rule, 51 characters).")

child("moto-helmet", "moto", "motorcycle-helmet-law-injury-lawyers-in-summerville", "Motorcycle Helmet Law Injury Lawyers in Summerville", 3150,
 "Motorcycle Helmet Law Injury Lawyers in Summerville | Call Us",
 "Motorcycle Helmet Law Injury Lawyers in Summerville at Frost Law Group explain what Section 56-5-3660 requires and how helmet questions arise. Call to talk.",
 "The age line at 21. South Carolina's helmet statute splits riders at age 21, so the page runs two tracks, riders under 21 (helmet, goggles or face shield, windscreen) and riders 21 and older (no statutory mandate), then how either track shows up in a claim.",
 ["What Motorcycle Helmet Law Injury Lawyers in Summerville Say Section 56-5-3660 Requires",
  "Riders Under 21, Goggles, and Windscreens, Explained by a Summerville Helmet Law Attorney",
  "How a Summerville Motorcycle Lawyer Responds When an Insurer Raises a Missing Helmet",
  "Head and Brain Injury Evidence a Summerville Motorcycle Injury Lawyer Develops",
  "Passenger Helmet Rules Under South Carolina Law for a Summerville Rider's Attorney",
  "Ask Motorcycle Helmet Law Injury Lawyers in Summerville How the Rule Affects You"],
 [U(P["moto"]), U(P["moto"]+"left-turn-motorcycle-accident-lawyers-in-summerville/"), U(P["cat"]),
  U(C["charleston"]+"motorcycle-accident-lawyers-in-charleston-county/"), CONTACT],
 ["t56c005", "factbook_pdf"], ["L8","L21 132 killed, 51 without helmet"],
 "Civil effect of helmet nonuse is NOT verified. Never state a legal rule that it reduces or does not reduce a claim. Say the insurer may raise it, and that fault and causation depend on the facts a lawyer reviews. Eye protection applies only to operators under 21, and a qualifying windscreen exempts them. Helmet share among killed riders, 75 wearing, 51 not, 6 unknown, of 132.")

child("moto-um", "moto", "uninsured-motorist-motorcycle-lawyers-in-summerville", "Uninsured Motorist Motorcycle Lawyers in Summerville", 3050,
 "Uninsured Motorist Motorcycle Lawyers in Summerville",
 "Uninsured Motorist Motorcycle Lawyers in Summerville at Frost Law Group use your own policy when the at-fault driver has no insurance. Call for a free consultation.",
 "Three kinds of missing coverage. The page takes the three ways a rider ends up without the other driver's insurance (the driver had none, the driver fled, the driver had too little) and follows each to the part of the rider's own policy that answers it.",
 ["How Uninsured Motorist Motorcycle Lawyers in Summerville Use Your Own Policy",
  "When the Driver Had No Insurance, a Summerville Motorcycle UM Attorney's First Steps",
  "When the Driver Fled, the Rules a Summerville Motorcycle Hit and Run Lawyer Follows",
  "When the Policy Is Too Small, Underinsured Coverage With a Summerville Rider Attorney",
  "Insurer Deadlines a Summerville Motorcycle Insurance Claim Lawyer Enforces",
  "Talk With Uninsured Motorist Motorcycle Lawyers in Summerville About Your Policy"],
 [U(P["moto"]), U(P["car"]+"hit-and-run-accident-lawyers-in-summerville/"), U(P["moto"]+"left-turn-motorcycle-accident-lawyers-in-summerville/"),
  U(C["berkeley"]+"motorcycle-accident-lawyers-in-berkeley-county/"), CONTACT],
 ["t38c077", "doi_auto"], ["L19","L4","L5"],
 "38-77-250 policy-limit disclosure within 30 days of a qualifying sworn request. 38-77-350(E) adds UM and UIM at liability limits when the signed offer form is not returned within 30 days, state it only exactly as R1 records it. Keyphrase alone as SEO title (house rule, 52 characters).")

child("ride-uber", "ride", "uber-accident-lawyers-in-summerville", "Uber Accident Lawyers in Summerville", 3150,
 "Uber Accident Lawyers in Summerville | Call Frost First",
 "Uber Accident Lawyers in Summerville at Frost Law Group handle claims for passengers, drivers, and others hurt in an Uber crash. Call for a free consultation.",
 "Three seats. The page asks where you were when the Uber crash happened (in the back seat, in another car or on foot, or behind the Uber driver's own wheel), because each seat leads to a different claim and a different policy.",
 ["How Uber Accident Lawyers in Summerville Handle a Passenger's Injury Claim",
  "When an Uber Driver Hits Your Car, How a Summerville Rideshare Crash Lawyer Proceeds",
  "Pedestrians and Cyclists Struck by Uber Drivers Near Summerville and Their Injury Attorney",
  "Claims for Uber Drivers Hurt by Other Motorists With a Summerville Injury Lawyer",
  "How a Summerville Uber Crash Attorney Matches the Trip Record to Coverage",
  "Call Uber Accident Lawyers in Summerville From Wherever You Are Recovering"],
 [U(P["ride"]), U(P["ride"]+"lyft-accident-lawyers-in-summerville/"), U(P["car"]), U(P["cat"]), CONTACT],
 ["t58c023", "dmv_reports"], ["L4","L6","L21 pedestrians"],
 "Uber's own policy limits and procedures are NOT verified. State only the statute's requirements. Do not name Uber features or apps beyond what is common knowledge (the app and the trip record).")

child("ride-lyft", "ride", "lyft-accident-lawyers-in-summerville", "Lyft Accident Lawyers in Summerville", 3100,
 "Lyft Accident Lawyers in Summerville | Ask Us Today",
 "Lyft Accident Lawyers in Summerville at Frost Law Group hold Lyft and its drivers to South Carolina's rideshare rules after a crash. Call for a free consultation.",
 "The statute's checklist. The page walks the obligations South Carolina's TNC Act places on the company and its drivers (driver screening, required coverage, crash disclosures, records) and shows what each obligation means to an injured person.",
 ["What Lyft Accident Lawyers in Summerville Check Under the TNC Act",
  "Driver Screening Records a Summerville Lyft Crash Attorney Can Raise",
  "Coverage Requirements a Summerville Lyft Injury Lawyer Holds the Company To",
  "Crash Disclosures a Lyft Driver Owes and How a Summerville Attorney Uses Them",
  "How a Summerville Lyft Passenger Injury Lawyer Handles Fault and Seat Belt Questions",
  "Lyft Accident Lawyers in Summerville Who Explain Your Options in Plain Terms"],
 [U(P["ride"]), U(P["ride"]+"uber-accident-lawyers-in-summerville/"), U(P["car"]+"hit-and-run-accident-lawyers-in-summerville/"), U(P["car"]), CONTACT],
 ["t58c023", "t38c077"], ["L5","L7","L17"],
 "Lyft's own policy limits and procedures are NOT verified. The seat belt statute 56-5-6540(C) makes non-use inadmissible, state it exactly. Must not repeat the Uber page's three-seat structure or its sentences.")

child("slip-retail", "slip", "retail-slip-and-fall-lawyers-in-summerville", "Retail Slip and Fall Lawyers in Summerville", 3200,
 "Retail Slip and Fall Lawyers in Summerville | Speak With Us",
 "Retail Slip and Fall Lawyers in Summerville at Frost Law Group prove what a store knew about the hazard that caused your fall. Call for a free consultation today.",
 "The store floor plan. The page walks a store the way a shopper does (entrance and mats, produce and freezer aisles, displays and shelving, checkout and restrooms) and names the notice question each area raises.",
 ["What Retail Slip and Fall Lawyers in Summerville Look for in a Store Aisle",
  "Produce, Freezer, and Spill Zones a Summerville Grocery Store Fall Lawyer Knows",
  "Entrance Mats and Wet Weather Floors in a Summerville Store Fall Attorney's Case",
  "Inspection Logs and Video a Summerville Retail Injury Lawyer Requests",
  "Store Incident Reports and Insurer Calls a Summerville Shopping Injury Attorney Handles",
  "Ask Retail Slip and Fall Lawyers in Summerville to Review What the Store Knew"],
 [U(P["slip"]), U(P["slip"]+"premises-liability-lawyers-in-summerville/"), U(P["slip"]+"apartment-injury-lawyers-in-summerville/"), HOME, CONTACT],
 ["wintersteen"], ["L6","L7","L1"],
 "Wintersteen (Food Lion) and Garvin (Bi-Lo) are real cases and may be described by their facts as reported. Never name a Summerville store or claim a store's practices.")

child("slip-apt", "slip", "apartment-injury-lawyers-in-summerville", "Apartment Injury Lawyers in Summerville", 3300,
 "Apartment Injury Lawyers in Summerville | Call Us Today",
 "Apartment Injury Lawyers in Summerville at Frost Law Group explain landlord duties under South Carolina's Residential Landlord and Tenant Act. Call for a free review.",
 "Inside your unit and outside your door. Landlord duties differ between common areas the landlord controls and the unit the tenant leases, so the page moves from the parking lot, walkways and stairs inward to the unit, then to code items and security.",
 ["How Apartment Injury Lawyers in Summerville Use the Residential Landlord and Tenant Act",
  "Stairs, Walkways, and Parking Areas a Summerville Apartment Complex Injury Attorney Examines",
  "Repairs Inside Your Unit and the Notice a Summerville Tenant Injury Lawyer Needs",
  "Smoke Detector and Code Violation Claims a Summerville Rental Injury Lawyer Handles",
  "When a Summerville Apartment Injury Attorney Can Raise a Security Failure",
  "Apartment Injury Lawyers in Summerville Who Understand Your Lease and Your Injury"],
 [U(P["slip"]), U(P["slip"]+"retail-slip-and-fall-lawyers-in-summerville/"), U(P["slip"]+"premises-liability-lawyers-in-summerville/"),
  U(P["dog"]+"dog-bite-insurance-claim-lawyers-in-summerville/"), CONTACT],
 ["t27c040"], ["L17","L2"],
 "Residential landlords generally owe tenants no security duty (Cramer). Wright v. PRG (2019) allows liability only when a landlord voluntarily undertakes security, and lighting or shrubbery alone does not count. State exactly that. Fair v. United States limits 'fit and habitable' to the physical state of the premises.")

child("slip-prem", "slip", "premises-liability-lawyers-in-summerville", "Premises Liability Lawyers in Summerville", 3400,
 "Premises Liability Lawyers in Summerville | Talk to Our Team",
 "Premises Liability Lawyers in Summerville at Frost Law Group handle injuries from falling objects, broken stairs, poor security, and unsafe property. Call today.",
 "What kind of hazard hurt you. The page sorts premises cases by the hazard (falling merchandise, stairs and railings, lighting, criminal attacks, public property, children on the land) and names the South Carolina rule that governs each.",
 ["Which Hazards Premises Liability Lawyers in Summerville Handle",
  "Falling Merchandise and Overhead Hazards a Summerville Property Injury Lawyer Investigates",
  "The Bass v. Gopal Test a Summerville Negligent Security Attorney Applies",
  "Stairs, Railings, and Lighting Defects a Summerville Property Owner Liability Attorney Proves",
  "Government Property Injuries and the Tort Claims Act Limits a Summerville Lawyer Explains",
  "How a Summerville Premises Lawyer Handles Injuries to Children on Someone Else's Land",
  "Premises Liability Lawyers in Summerville Who Will Review What Happened on the Property"],
 [U(P["slip"]), U(P["slip"]+"retail-slip-and-fall-lawyers-in-summerville/"), U(P["slip"]+"apartment-injury-lawyers-in-summerville/"),
  U(P["dog"]+"dog-bite-strict-liability-lawyers-in-summerville/"), CONTACT],
 ["bass", "t15c078"], ["L1","L2","L18"],
 "Keyphrase in the manifest was 'South Carolina premises liability lawyer'. The house rule makes the H1 the keyphrase.")

child("dog-strict", "dog", "dog-bite-strict-liability-lawyers-in-summerville", "Dog Bite Strict Liability Lawyers in Summerville", 3100,
 "Dog Bite Strict Liability Lawyers in Summerville | Call Today",
 "Dog Bite Strict Liability Lawyers in Summerville at Frost Law Group read Section 47-3-110 line by line to show who is liable. Call for a free consultation today.",
 "Reading 47-3-110 line by line. Each section takes one clause of the statute (bites or otherwise attacks, owner or person having the dog in care or keeping, public place or lawfully in a private place, the provocation and police dog exceptions) and explains what it means in a real claim.",
 ["How Dog Bite Strict Liability Lawyers in Summerville Read Section 47-3-110",
  "Owners and Keepers a Summerville Dog Attack Attorney Can Name",
  "Public Places and Lawful Visits That Qualify a Summerville Dog Bite Lawyer's Claim",
  "Provocation and Police Dog Exceptions a Summerville Dog Injury Lawyer Anticipates",
  "Attacks Without a Bite and What a Summerville Animal Attack Lawyer Proves",
  "Dog Bite Strict Liability Lawyers in Summerville Who Know the Statute Word for Word"],
 [U(P["dog"]), U(P["dog"]+"child-dog-bite-injury-lawyers-in-summerville/"), U(P["dog"]+"dog-bite-insurance-claim-lawyers-in-summerville/"),
  U(P["slip"]+"premises-liability-lawyers-in-summerville/"), CONTACT],
 ["t47c003"], ["L17","L6"],
 "Quote statute words briefly and exactly from R2. Clea v. Odom and Bruce v. Durney (landlord not liable for a tenant's dog) may be described.")

child("dog-child", "dog", "child-dog-bite-injury-lawyers-in-summerville", "Child Dog Bite Injury Lawyers in Summerville", 3250,
 "Child Dog Bite Injury Lawyers in Summerville | Talk With Us",
 "Child Dog Bite Injury Lawyers in Summerville at Frost Law Group protect a child's claim through treatment, deadlines, and court approval. Call for a free review.",
 "Milestones in a child's claim. The page follows a child's case from the emergency room through scarring and future care, the one-year-after-18 deadline, and the court approval a settlement needs.",
 ["How Child Dog Bite Injury Lawyers in Summerville Protect a Young Victim's Claim",
  "Pediatric Emergency Care Near Summerville and the Records a Child Bite Lawyer Collects",
  "Scarring and Facial Injuries in a Summerville Child Dog Attack Attorney's Case",
  "The One Year After 18 Rule a Summerville Child Injury Lawyer Explains",
  "Why a Summerville Dog Bite Attorney for Children Needs Court Approval of a Settlement",
  "Call Child Dog Bite Injury Lawyers in Summerville Who Treat Your Family With Care"],
 [U(P["dog"]), U(P["dog"]+"dog-bite-strict-liability-lawyers-in-summerville/"), U(P["dog"]+"dog-bite-insurance-claim-lawyers-in-summerville/"),
  U(P["cat"]), CONTACT],
 ["t62c005", "t15c003"], ["L6 pediatric ER","L7 pediatric-ready","L8 MUSC Pediatric Level I"],
 "Settlements of a child's claim over $25,000 net need circuit court approval (62-5-433). Probate courts handle minor settlements under $25,000 (sccourts.org). Tolling of a parent's own claim (medical bills) under 15-3-40 is NOT verified, do not state it. Never state where EMS will take a child.")

child("dog-ins", "dog", "dog-bite-insurance-claim-lawyers-in-summerville", "Dog Bite Insurance Claim Lawyers in Summerville", 3050,
 "Dog Bite Insurance Claim Lawyers in Summerville | Call Us",
 "Dog Bite Insurance Claim Lawyers in Summerville at Frost Law Group pursue the owner's policy so you are not suing a neighbor. Call for a free, confidential review.",
 "Claims against people you know. Many bites involve a neighbor, a friend or a relative's dog, so the page is organized around the relationship (neighbor, relative, friend, landlord's tenant, stranger) and shows how the claim runs against a policy rather than the person.",
 ["How Dog Bite Insurance Claim Lawyers in Summerville Pursue a Policy, Not a Friend",
  "When a Relative's Dog Bites, What a Summerville Dog Bite Claim Attorney Explains",
  "Homeowner and Renter Policies a Summerville Dog Attack Insurance Lawyer Checks",
  "Landlord Coverage Questions a Summerville Dog Bite Injury Lawyer Sorts Out",
  "What an Adjuster Asks For and How a Summerville Dog Bite Attorney Responds",
  "Dog Bite Insurance Claim Lawyers in Summerville Who Keep the Claim Neighborly"],
 [U(P["dog"]), U(P["dog"]+"dog-bite-strict-liability-lawyers-in-summerville/"), U(P["dog"]+"child-dog-bite-injury-lawyers-in-summerville/"),
  U(P["slip"]+"apartment-injury-lawyers-in-summerville/"), CONTACT],
 ["t47c003"], ["L17","L6"],
 "Insurance policy terms vary. Never state what a particular policy covers or excludes as fact. Say policies often, generally, or may. No statute governs homeowner dog coverage in the research, do not invent one.")

child("wd-car", "wd", "fatal-car-accident-lawyers-in-summerville", "Fatal Car Accident Lawyers in Summerville", 3150,
 "Fatal Car Accident Lawyers in Summerville | Speak With Us",
 "Fatal Car Accident Lawyers in Summerville at Frost Law Group answer a family's first questions after a deadly crash. Call for a free, confidential consultation.",
 "Family questions in the order they come up. Each H2 is a question a grieving family actually asks, in the order they tend to ask it (what happens first, who investigated, who signs, what about the criminal case, how long do we have).",
 ["What Fatal Car Accident Lawyers in Summerville Handle First for a Family",
  "Which Agencies Investigate a Deadly Summerville Crash and What a Fatal Crash Attorney Requests",
  "Who Signs for the Family When a Summerville Car Crash Death Lawyer Files",
  "How a Criminal Charge Affects the Family's Claim With a Summerville Deadly Crash Lawyer",
  "How Long a Family Has to File With a Summerville Wrongful Death Car Accident Attorney",
  "Fatal Car Accident Lawyers in Summerville Who Will Talk With Your Family First"],
 [U(P["wd"]), U(P["wd"]+"survival-action-lawyers-in-summerville/"), U(P["wd"]+"fatal-truck-accident-lawyers-in-summerville/"), U(P["car"]), CONTACT],
 ["dmv_reports", "t15c051"], ["L4 Traffic Safety Unit","L5 Troop Nine MAIT","L15 37 killed","L19"],
 "Troop Nine is the Highway Patrol's Multi-disciplinary Accident Investigation Team. Never state which agency will respond to a specific crash.")

child("wd-survival", "wd", "survival-action-lawyers-in-summerville", "Survival Action Lawyers in Summerville", 3100,
 "Survival Action Lawyers in Summerville | Ask Our Team",
 "Survival Action Lawyers in Summerville at Frost Law Group pursue the losses a loved one suffered before death under South Carolina law. Call for a free review.",
 "Proof of the time between crash and death. The survival action recovers what the person suffered while alive, so the page follows the evidence of that interval (EMS records, emergency notes, witnesses, medical bills, funeral costs) and how it moves through the estate.",
 ["What Survival Action Lawyers in Summerville Recover Under Section 15-5-90",
  "Proving Conscious Pain and Suffering With a Summerville Survival Claim Attorney",
  "Medical Bills and Funeral Costs a Summerville Survival Claim Lawyer Documents",
  "How a Summerville Estate Claim Lawyer Handles Survival Damages Through Probate",
  "When a Summerville Survival Action Attorney Files Alongside a Wrongful Death Claim",
  "Survival Action Lawyers in Summerville Who Explain the Estate Side Plainly"],
 [U(P["wd"]), U(P["wd"]+"fatal-car-accident-lawyers-in-summerville/"), U(P["wd"]+"fatal-truck-accident-lawyers-in-summerville/"),
  U(P["cat"]), CONTACT],
 ["t15c005", "t62c003"], ["L20","L8"],
 "Keyphrase in the manifest was 'South Carolina survival action lawyer'. The house rule makes the H1 the keyphrase. Funeral expenses under 15-5-100 exactly as R2 records. A separate limitations rule for survival claims measured from death is NOT verified. Pre-death medical expense recovery case law is NOT verified beyond the statute text, hedge.")

child("wd-truck", "wd", "fatal-truck-accident-lawyers-in-summerville", "Fatal Truck Accident Lawyers in Summerville", 3350,
 "Fatal Truck Accident Lawyers in Summerville | Call Us Today",
 "Fatal Truck Accident Lawyers in Summerville at Frost Law Group examine the carrier's hiring, testing, maintenance, and logs after a deadly crash. Call us today.",
 "Carrier duties, one regulation at a time. The page looks past the driver to the motor carrier and takes its duties one federal regulation at a time (qualification files, post-crash testing, maintenance, hours of service, insurance).",
 ["How Fatal Truck Accident Lawyers in Summerville Look Past the Driver to the Carrier",
  "Driver Qualification Files a Summerville Deadly Truck Crash Attorney Demands",
  "Post-Crash Drug and Alcohol Testing Deadlines a Summerville Truck Wreck Death Lawyer Checks",
  "Maintenance and Inspection Records in a Summerville Fatal 18 Wheeler Lawyer's Case",
  "Hours of Service Violations a Summerville Truck Wrongful Death Attorney Traces",
  "Punitive Damages and Insurance Limits a Summerville Trucking Death Attorney Weighs",
  "Fatal Truck Accident Lawyers in Summerville Who Start With the Carrier's Records"],
 [U(P["wd"]), U(P["wd"]+"survival-action-lawyers-in-summerville/"), U(P["truck"]), U(P["truck"]+"truck-driver-fatigue-accident-lawyers-in-summerville/"), CONTACT],
 ["ecfr_382_303", "ecfr_391_51"], ["L21 CMV 145 killed, fatal up 15%","L5"],
 "Post-accident testing, alcohol within 2 hours (stop trying at 8), drugs within 32 hours, exactly as R2 records.")

# ---------------------------------------------------------------- PHASE D, county children
def cchild(id, ckey, slug, h1, target, title, desc, device, h2, links, outbound, notes=""):
    url = U(C[ckey] + slug + "/")
    PAGES.append(pg(id=id, phase="D", type="County child page", h1=h1, url=url, slug=C[ckey]+slug+"/",
      parent=U(C[ckey]), wp_title=h1, kp=h1, words=(3040, 3700), target=target, replaces="New page", redirect_from=[],
      title=title, desc=desc, device=device, h2=h2, first_link=(U(C[ckey]), "'Frost Law Group' pointing to this page's county parent"),
      links=links, outbound=outbound, local=[f"county pack: {ckey.capitalize()} entry"], images="child", notes=notes))

cchild("chs-car", "charleston", "car-accident-lawyers-in-charleston-county", "Car Accident Lawyers in Charleston County", 3200,
 "Car Accident Lawyers in Charleston County | Call Frost First",
 "Car Accident Lawyers in Charleston County at Frost Law Group prove distraction, failure to yield, and tailgating after a wreck. Call for a free consultation.",
 "The distracted driver as the default suspect. Distraction is the second most listed factor in Charleston County, a pattern unusual in the footprint, so each section asks how distraction is proved and how it combines with the county's other top factors.",
 ["How Car Accident Lawyers in Charleston County Prove Distraction",
  "Failure to Yield Crashes a Charleston County Auto Accident Attorney Handles",
  "Following Too Closely on US 17 and I-26 With a Charleston County Car Crash Lawyer",
  "Mount Pleasant, North Charleston, and James Island Wrecks a Charleston County Car Lawyer Takes",
  "Serious Injury Claims and Policy Limits a Charleston County Car Wreck Attorney Confronts",
  "Car Accident Lawyers in Charleston County Who Answer Your Questions Directly"],
 [U(C["charleston"]), U(P["car"]), U(C["charleston"]+"truck-accident-lawyers-in-charleston-county/"), U(C["berkeley"]+"car-accident-lawyers-in-berkeley-county/"), CONTACT],
 ["doi_auto", "dph_trauma"],
 "Never compare the county listed-factor count (2,965) to the statewide primary-factor count.")

cchild("chs-truck", "charleston", "truck-accident-lawyers-in-charleston-county", "Truck Accident Lawyers in Charleston County", 3350,
 "Truck Accident Lawyers in Charleston County | Ask Us Today",
 "Truck Accident Lawyers in Charleston County at Frost Law Group handle semi and commercial vehicle crash claims on I-26, I-526, and US 52. Call for a free review.",
 "Interchange by interchange. All five of the worst intersections in Charleston County are on I-26, so the page travels the interstate interchanges and the heavy corridors and asks, at each, which trucking rules and records matter.",
 ["Why Truck Accident Lawyers in Charleston County Study the I-26 Interchanges",
  "I-526 and US 52 Crash Claims a Charleston County Semi Truck Attorney Handles",
  "Commercial Vehicle Rules a Charleston County 18 Wheeler Lawyer Applies",
  "Out of State Truck Drivers in a Charleston County Trucking Accident Attorney's Case",
  "Trauma Care at MUSC and Trident After a Charleston County Truck Crash, With a Lawyer",
  "Talk With Truck Accident Lawyers in Charleston County About the Carrier's Records"],
 [U(C["charleston"]), U(P["truck"]), U(P["truck"]+"tractor-trailer-accident-lawyers-in-summerville/"), U(C["charleston"]+"motorcycle-accident-lawyers-in-charleston-county/"), CONTACT],
 ["ecfr_395_3", "dph_trauma"],
 "Never name Georgia or any other state for out-of-state drivers, say 'drivers based in other states'. Never state where EMS will take a patient. No port or freight volume claims, they are not verified.")

cchild("chs-moto", "charleston", "motorcycle-accident-lawyers-in-charleston-county", "Motorcycle Accident Lawyers in Charleston County", 3100,
 "Motorcycle Accident Lawyers in Charleston County | Call Us",
 "Motorcycle Accident Lawyers in Charleston County at Frost Law Group document serious rider injuries and pursue every available policy. Call for a free review.",
 "Injury severity and medical proof. Charleston County leads the state in serious injury collisions and has two trauma centers, so the page is built around the medical record a rider's claim depends on, from the scene to long-term care.",
 ["What Motorcycle Accident Lawyers in Charleston County Document After a Serious Crash",
  "US 17 and Island Road Riding and the Claims a Charleston County Biker Lawyer Handles",
  "Helmet Law, Lane Rules, and Fault in a Charleston County Motorcycle Injury Attorney's Case",
  "Uninsured Drivers and a Charleston County Motorcycle Crash Attorney's Coverage Search",
  "Filing in the Ninth Circuit at 100 Broad Street for a Charleston County Rider's Lawyer",
  "Call Motorcycle Accident Lawyers in Charleston County Who Understand the Ride"],
 [U(C["charleston"]), U(P["moto"]), U(P["moto"]+"motorcycle-helmet-law-injury-lawyers-in-summerville/"), U(C["charleston"]+"car-accident-lawyers-in-charleston-county/"), CONTACT],
 ["dph_trauma", "t56c005"],
 "The pack has no Charleston County motorcycle counts. Use statewide 2024 motorcycle figures labeled statewide. Civil effect of helmet nonuse NOT verified.")

cchild("brk-car", "berkeley", "car-accident-lawyers-in-berkeley-county", "Car Accident Lawyers in Berkeley County", 3150,
 "Car Accident Lawyers in Berkeley County | Call Us Today",
 "Car Accident Lawyers in Berkeley County at Frost Law Group handle speed, lane change, and run off road crash claims from Goose Creek to Moncks Corner. Call today.",
 "Too fast for conditions. Berkeley County's top listed factor is speed for conditions, the reverse of its neighbors, so the page organizes car crash claims around speed and the lane and road-departure crashes that follow from it.",
 ["Why Car Accident Lawyers in Berkeley County Start With Speed for Conditions",
  "US 52 and US 176 Crash Claims a Berkeley County Auto Accident Attorney Handles",
  "Improper Lane Changes and Run Off Road Wrecks a Berkeley County Car Crash Lawyer Sees",
  "Summerville's Berkeley County Side and the Car Wreck Claims a Local Attorney Takes",
  "Court and Insurance Steps a Berkeley County Car Accident Attorney Follows",
  "Talk to Car Accident Lawyers in Berkeley County Before the Adjuster Calls Back"],
 [U(C["berkeley"]), U(P["car"]), U(C["berkeley"]+"truck-accident-lawyers-in-berkeley-county/"), U(C["charleston"]+"car-accident-lawyers-in-charleston-county/"), CONTACT],
 ["doi_auto", "t56c005"],
 "The Berkeley parent covers the College Park Road and Jedburg Road interchanges, so this page uses US 52 (653) and US 176 (569) and the Nexton Parkway interchange (Exit 197) instead. Summerville Police investigated 416 collisions in Berkeley County in 2024.")

cchild("brk-truck", "berkeley", "truck-accident-lawyers-in-berkeley-county", "Truck Accident Lawyers in Berkeley County", 3300,
 "Truck Accident Lawyers in Berkeley County | Call Frost First",
 "Truck Accident Lawyers in Berkeley County at Frost Law Group handle semi, gravel truck, and commercial vehicle crash claims on I-26 and US 52. Call for a review.",
 "Interstate against US route. Statewide, more fatal commercial vehicle collisions happened on US primary routes (43) than on interstates (36) in 2024, so the page sets Berkeley County's I-26 truck crashes against its US route and gravel truck exposure.",
 ["How Truck Accident Lawyers in Berkeley County Compare I-26 and US Route Crashes",
  "Heavy Trucks on US 52 and US 17A Near Moncks Corner and a Berkeley County Trucking Lawyer",
  "State Rules for In-State Trucks a Berkeley County Tractor Trailer Attorney Applies",
  "Load Securement and Gravel Truck Claims With a Berkeley County Truck Crash Lawyer",
  "Evidence Deadlines After a Berkeley County Semi Crash for a Trucking Accident Attorney",
  "Truck Accident Lawyers in Berkeley County Ready to Request the Carrier's Records"],
 [U(C["berkeley"]), U(P["truck"]), U(P["truck"]+"truck-driver-fatigue-accident-lawyers-in-summerville/"), U(C["berkeley"]+"motorcycle-accident-lawyers-in-berkeley-county/"), CONTACT],
 ["t56c005", "ecfr_382_303"],
 "US 17A exists in Berkeley per SCDOT. Do not write US 17. 56-5-4100 requires loads and coverings be securely fastened (2024) and sets rules for rock, gravel and stone haulers, exactly as R2 records.")

cchild("brk-moto", "berkeley", "motorcycle-accident-lawyers-in-berkeley-county", "Motorcycle Accident Lawyers in Berkeley County", 3050,
 "Motorcycle Accident Lawyers in Berkeley County | Talk to Us",
 "Motorcycle Accident Lawyers in Berkeley County at Frost Law Group handle rider injury claims across Goose Creek, Hanahan, and Moncks Corner. Call for a free review.",
 "Survivable crashes and long claims. Berkeley County's crash death rate (13.9 per 100,000) is among the lowest in the footprint, yet it still recorded 114 motorcyclist victims in 2024, so the page is about the rider who survives and the injury claim that follows.",
 ["What Motorcycle Accident Lawyers in Berkeley County See Behind the Low Death Rate",
  "Treatment Records a Berkeley County Biker Injury Lawyer Tracks After a Crash",
  "How a Berkeley County Motorcycle Crash Attorney Uses the Full-Lane Rule",
  "Speed for Conditions and a Berkeley County Motorcycle Injury Attorney's Proof",
  "Filing in Moncks Corner With a Berkeley County Rider Accident Lawyer",
  "Motorcycle Accident Lawyers in Berkeley County Who Take Rider Injuries Seriously"],
 [U(C["berkeley"]), U(P["moto"]), U(P["moto"]+"uninsured-motorist-motorcycle-lawyers-in-summerville/"), U(C["berkeley"]+"car-accident-lawyers-in-berkeley-county/"), CONTACT],
 ["t56c005", "dph_trauma"],
 "114 motorcyclist victims with 4 killed in Berkeley County 2024. Berkeley's 13.9 per 100,000 is the second lowest of the eight counties (Beaufort 13.3 is lowest), never call it the lowest.")

# ---------------------------------------------------------------- local hook inventory
LOCAL = {
 "L1": "Dorchester County Courthouse, 5200 East Jim Bilton Boulevard, St. George, SC 29477, Court of Common Pleas and General Sessions, First Judicial Circuit (sccourts.org).",
 "L2": "Troy Knight Judicial Complex, 212 Deming Way, Summerville. Houses Dorchester Family Court, the Summerville Magistrate Court and Central Bond Court.",
 "L3": "Summerville Municipal Court, 200 S Main Street, 2nd Floor. Traffic and criminal misdemeanor cases inside town limits. A town court, different from the magistrate court.",
 "L4": "Summerville Police Department, 108 North Cedar St. Directs people to CrashDocs for collision reports. Its Traffic Safety Unit includes officers trained in at-scene, technical and reconstruction collision investigation (summervillesc.gov).",
 "L5": "SC Highway Patrol Troop Six covers Beaufort, Berkeley, Charleston, Colleton, Dorchester and Jasper counties, headquartered at 2070 Northbrook Blvd, North Charleston. Post B covers Dorchester from the Colleton patrol office in Walterboro. Troop Nine is the Multi-disciplinary Accident Investigation Team (MAIT). Never say which troop responds to a crash.",
 "L6": "HCA Healthcare Summerville Hospital, 295 Midland Parkway, 174 beds, 24-hour ER and a 10-bed pediatric ER. Not a trauma center.",
 "L7": "Roper St. Francis Berkeley Hospital, 100 Callen Boulevard, Summerville mailing address but in Berkeley County, 24/7 emergency services with pediatric-ready accreditation. Not a trauma center.",
 "L8": "MUSC in Charleston, Adult Level I and the state's only Pediatric Level I trauma center. Trident Medical Center, North Charleston, Adult Level II. Say a patient may be taken there, never will be.",
 "L9": "Dorchester Road (SC 642) had 519 collisions and 6 deaths in Dorchester County in 2024, the most of any road in the county (SCDPS Fact Book, as recorded by officers). Dorchester Road at Old Trolley Road 53, at Ladson Road 49, at Bacons Bridge Road (SC 165) 41. SCDOT 2024 average daily traffic 45,300 between Old Trolley Road and the Charleston County line.",
 "L10": "US 17A is Main Street in Summerville (SCDOT). SCDOT 2024 average daily traffic 33,100 between 5th Street North and the Berkeley County line. I-26 Exit 199 is US 17A (North Main Street).",
 "L11": "US 78 is 5th Street North in Summerville (SCDOT). The Fact Book lists US-78 at SC-165 with 56 collisions in 2024, the most of any Dorchester intersection. Do not call that junction Bacons Bridge Road.",
 "L12": "Central Avenue is S-13 in Dorchester County, 198 collisions in 2024, fifth among Dorchester roads.",
 "L13": "I-26 interchanges near Summerville per SCDOT: Exit 194 Jedburg Road, Exit 197 Nexton Parkway, Exit 199 US 17A (North Main Street), Exit 203 College Park Road, all labeled Berkeley County, and Exit 205 US 78 (University Boulevard), Charleston County. 2024 average daily traffic on I-26 was 89,700 between US 17A and College Park Road and 107,600 between College Park Road and US 78. In Berkeley County, I-26 at College Park Road had 113 collisions and Jedburg Road at I-26 had 103 in 2024.",
 "L14": "Berlin G. Myers Parkway Phase III, a $160 million SCDOT project, opened fully to traffic in late April 2025. Never give it a route number.",
 "L15": "Dorchester County 2024 (Fact Book): 3,958 collisions, 32 fatal, 37 killed, 60 serious injury collisions with 81 seriously injured, 809 other injury collisions with 1,226 injured. Death rate 21.2 per 100,000, up from 8.8 in 2023. Most collisions 3 to 6 PM (972), most fatal 6 to 9 PM (9). Victims: 66 motorcyclists (7 killed), 36 pedestrians (4 killed), 18 bicyclists (1 killed). NHTSA estimates 19 alcohol-impaired deaths in Dorchester County in 2024, up from 8. 118 non-fatal DUI collisions.",
 "L16": "Who investigated Dorchester County collisions in 2024: Highway Patrol 1,517 (23 fatal), Summerville Police 1,321 (3 fatal), Sheriff's Office 590. Summerville Police also investigated 416 in Berkeley County and 21 in Charleston County.",
 "L17": "The Town of Summerville sits in three counties. Census 2025 estimates, 44,724 residents in the Dorchester part, 5,798 in Berkeley, 2,655 in Charleston. Population 50,915 at the 2020 Census, estimated 53,177 in 2025. Summerville is a town, not a city.",
 "L18": "South Carolina magistrates hear civil cases up to $7,500 (S.C. Code 22-3-10). Injury claims above that are filed in the Court of Common Pleas.",
 "L19": "SCDMV collision report copies by Form FR-50, $10 per report. The FR-10 insurance verification form goes back to SCDMV within 15 days of the officer handing it over (56-9-350). FR-309 within 15 days when no officer investigated a crash with injury, death or $1,000 in damage (56-5-1270).",
 "L20": "The SC Judicial Branch lists the Dorchester County Probate Judge at 5200 E Jim Bilton Blvd, St. George. No Summerville probate office is verified.",
 "L21": "Statewide 2024 Fact Book figures, see R3 section 1.",
}

if __name__ == "__main__":
    import plan_v2
    plan_v2.add_v2(PAGES, pg, U, P, C, HOME, PA, LOC, CONTACT, ABOUT, OUT)
    ids = [p["id"] for p in PAGES]
    assert len(ids) == len(set(ids)), (len(ids), len(set(ids)))
    urls = [p["url"] for p in PAGES]; assert len(set(urls)) == len(PAGES)
    kps = [p["kp"].lower() for p in PAGES]; assert len(set(kps)) == len(PAGES)
    mf = os.path.join(os.path.dirname(os.path.abspath(__file__)), "meta_final.json")
    if os.path.exists(mf):
        m = json.load(open(mf))
        for p in PAGES:
            if p["id"] in m["D"]: p["desc"] = m["D"][p["id"]]
            if p["id"] in m["T"]: p["title"] = m["T"][p["id"]]
    ho = os.path.join(os.path.dirname(os.path.abspath(__file__)), "h2_overrides.json")
    if os.path.exists(ho):
        H = json.load(open(ho))
        for p in PAGES:
            for old, new in H.get(p["id"], {}).items():
                p["h2"] = [new if h == old else h for h in p["h2"]]
    json.dump({"pages": PAGES, "outbound": OUT, "local": LOCAL}, open(os.path.join(os.path.dirname(__file__), "plan.json"), "w"), indent=1)
    print("pages", len(PAGES))
